- openstack_ansible/common.py
- openstack_ansible/config.py
- openstack_ansible/const.py
- openstack_ansible/openstack_ansible.py
Add code for converting openstack resources config to Ansible playbooks.
> Add openstack to ansible (transible) converter

- doc/design.md
This depends on PR #2. If PR #2 merges amended, i'll rebase here.
> Rough draft of workflow on Ansible level

- doc/design.md
This list was originally for Tmit PoC (https://gitlab.com/jistr/tmit),
and i think a lot of it could apply for OS-Migrate, so i post it here,
with minor amendments.
> High-level development goals

- os_migrate/playbooks/import_networks.yml
- os_migrate/plugins/module_utils/exc.py
- os_migrate/plugins/module_utils/filesystem.py
- os_migrate/plugins/module_utils/network.py
- os_migrate/plugins/module_utils/serialization.py
- os_migrate/plugins/modules/export_network.py
- os_migrate/plugins/modules/import_network.py
- os_migrate/plugins/modules/read_resources.py
- os_migrate/roles/import_networks/tasks/main.yml
- os_migrate/tests/unit/fixtures.py
- os_migrate/tests/unit/test_filesystem.py
- os_migrate/tests/unit/test_network.py
- os_migrate/tests/unit/test_serialization.py
- tests/func/run/network.yml
- toolbox/build/venv-requirements.txt
> Use network class from the .network. openstacksdk submodule

- .github/workflows/functional-all.yml
- scripts/publish.sh
- toolbox/build/build.sh
This patch builds on each merge a new version of the collection,
then this build should be published to Galaxy.
> Build and publish the collection to Galaxy

- .gitignore
- Makefile
- scripts/build.sh
- scripts/publish.sh
> Make 'build.sh' use 'releases' dir and make 'publish.sh' use 'build.sh'

- doc/design.md
This is part of the design doc which i forgot to transfer from Tmit
[1]. It is useful to have this rationale captured.
[1] https://gitlab.com/jistr/tmit/blob/4559f58718f133e8ce44e50f31fef8485ff66fc7/doc/design.md#L107-121
> Design doc - challenges of problem domain and how we deal with them

- .github/workflows/functional-all.yml
We need to wait until https://review.opendev.org/#/c/704136/
is merged to remove the pin.
Fixes #34
> Wait until the Devstack fix is merged

- os_migrate/plugins/module_utils/filesystem.py
- os_migrate/plugins/module_utils/network.py
- os_migrate/plugins/module_utils/serialization.py
- os_migrate/roles/export_networks/tasks/main.yml
- os_migrate/tests/unit/test_filesystem.py
- os_migrate/tests/unit/test_serialization.py
- tests/func/ansible.cfg
- tests/func/idempotence/all.yml
- tests/func/idempotence/network.yml
- tests/func/test_all.yml
- tests/func/test_network.yml
Depends on PR #23 and #27 
(See commit msgs for details what this PR does.)
> Export idempotence

- os_migrate/plugins/filter/stringfilter.py
- os_migrate/roles/export_networks/defaults/main.yml
- os_migrate/roles/export_networks/defauts/main.yml
- os_migrate/roles/export_networks/tasks/main.yml
- os_migrate/tests/unit/test_stringfilter.py
- tests/func/idempotence/network.yml
- tests/func/run/network.yml
> Advanced name filtering (exact match, regex)

- toolbox/vagrant/ansible/roles/devstack/tasks/config.yml
- toolbox/vagrant/ansible/roles/devstack/tasks/prereqs.yml
- toolbox/vagrant/ansible/roles/devstack/tasks/start.yml
- toolbox/vagrant/vagrant-destroy
All issues fixed / worked around except #61 where we have a workaround and we're waiting for a libpod fix.
> Fix Vagrant + Devstack developer environment

- .github/workflows/functional-all.yml
> Functional CI fixes

- os_migrate/plugins/module_utils/network.py
- os_migrate/plugins/module_utils/reference.py
- os_migrate/plugins/modules/export_security_group_rules.py
- os_migrate/roles/export_security_group_rules/tasks/main.yml
- os_migrate/roles/export_security_groups/tasks/main.yml
- os_migrate/tests/unit/fixtures.py
- os_migrate/tests/unit/test_security_group_rule.py
> Use id-based iteration for Security Groups and Security Group Rules

- os_migrate/plugins/modules/export_security_group.py
- os_migrate/plugins/modules/export_security_group_rules.py
- tests/func/clean/all.yml
- tests/func/clean/security_group.yml
- tests/func/clean/security_group_rule.yml
- tests/func/run/all.yml
- tests/func/run/security_group.yml
- tests/func/run/security_group_rule.yml
- tests/func/seed/all.yml
- tests/func/seed/security_group.yml
- tests/func/seed/security_group_rule.yml
Include functional tests from exporting security groups and security group rules
Closes: #80
Closes: #81
> Include functional tests from exporting security groups and security group rules

- os_migrate/playbooks/import_security_group_rules.yml
- os_migrate/playbooks/import_security_groups.yml
- os_migrate/plugins/module_utils/network.py
- os_migrate/plugins/module_utils/reference.py
- os_migrate/plugins/modules/import_security_group.py
- os_migrate/plugins/modules/import_security_group_rule.py
- os_migrate/roles/import_security_group_rules/defaults/main.yml
- os_migrate/roles/import_security_group_rules/tasks/main.yml
- os_migrate/roles/import_security_groups/defaults/main.yml
- os_migrate/roles/import_security_groups/tasks/main.yml
- os_migrate/tests/unit/test_security_group.py
- os_migrate/tests/unit/test_security_group_rule.py
- tests/func/run/security_group.yml
- tests/func/run/security_group_rule.yml
> Import security groups and rules

- os_migrate/plugins/modules/export_security_group_rules.py
We are writing only the last item in the array to the output file.
Closes:#100
> Write resource correctly when iterating over resources

- scripts/linters.sh
- scripts/publish.sh
This PR enables the bashate check and fix the bash nits around.
> Fix bashate

- os_migrate/plugins/module_utils/router.py
- os_migrate/plugins/modules/export_router.py
- os_migrate/tests/unit/fixtures.py
- os_migrate/tests/unit/test_router.py
The router functionality is just export right now, let's first
refactor it as Resource subclass before we add import.
> Refactor router export via Resource subclass

- os_migrate/plugins/module_utils/router.py
- os_migrate/plugins/modules/export_router.py
- os_migrate/plugins/modules/import_router.py
- os_migrate/roles/import_routers/defaults/main.yml
- os_migrate/roles/import_routers/tasks/main.yml
- os_migrate/tests/unit/fixtures.py
- os_migrate/tests/unit/test_router.py
- tests/func/run/router.yml
Import routers. Some params were refused on the router creation
request so i had to move them to 'info'.
> Add basic import of Routers

- .github/workflows/consistency-functional.yml
- scripts/linters.sh
> Start the container MySQL service

- tests/func/idempotence/all.yml
- tests/func/idempotence/subnet.yml
This patch adds idempotence test for subnets.
partially-addresses #21
> Subnet Idempotence Testing

- os_migrate/playbooks/export_router_interfaces.yml
- os_migrate/playbooks/import_router_interfaces.yml
- os_migrate/plugins/module_utils/const.py
- os_migrate/plugins/module_utils/exc.py
- os_migrate/plugins/module_utils/reference.py
- os_migrate/plugins/module_utils/resource.py
- os_migrate/plugins/module_utils/router.py
- os_migrate/plugins/module_utils/router_interface.py
- os_migrate/plugins/modules/export_router_interfaces.py
- os_migrate/plugins/modules/import_router_interface.py
- os_migrate/roles/export_router_interfaces/tasks/main.yml
- os_migrate/roles/import_router_interfaces/defaults/main.yml
- os_migrate/roles/import_router_interfaces/tasks/main.yml
- os_migrate/tests/unit/test_router_interface.py
- tests/func/clean/router.yml
- tests/func/clean/subnet.yml
- tests/func/run/all.yml
- tests/func/run/router_interface.yml
- tests/func/seed/router.yml
- tests/func/seed/subnet.yml
Import and export of router interfaces.
Closes #92 
Closes #93
> Router Interfaces

- os_migrate/plugins/module_utils/reference.py
- os_migrate/plugins/module_utils/security_group_rule.py
- os_migrate/plugins/modules/export_security_group_rules.py
- os_migrate/plugins/modules/import_security_group_rule.py
- os_migrate/tests/unit/fixtures.py
- os_migrate/tests/unit/test_security_group_rule.py
This is the third patch for the OOP refactor of the security groups and rules.
> OOP sec group rules

- os_migrate/galaxy.yml
- os_migrate/plugins/module_utils/const.py
- os_migrate/roles/export_networks/meta/main.yml
- os_migrate/roles/export_router_interfaces/meta/main.yml
- os_migrate/roles/export_routers/meta/main.yml
- os_migrate/roles/export_security_group_rules/meta/main.yml
- os_migrate/roles/export_security_groups/meta/main.yml
- os_migrate/roles/export_subnets/meta/main.yml
- os_migrate/roles/import_networks/meta/main.yml
- os_migrate/roles/import_router_interfaces/meta/main.yml
- os_migrate/roles/import_routers/meta/main.yml
- os_migrate/roles/import_security_group_rules/meta/main.yml
- os_migrate/roles/import_security_groups/meta/main.yml
- os_migrate/roles/import_subnets/meta/main.yml
- os_migrate/roles/validate_data_dir/meta/main.yml
- os_migrate/tests/unit/test_serialization.py
- scripts/publish.sh
- tests/func/data/validate_data_dir/invalid/networks-duplicate.yml
- tests/func/data/validate_data_dir/invalid/networks.yml
- tests/func/data/validate_data_dir/valid/networks.yml
There are several checks we need to pass in order to be able
to publish the collection in both Galaxy and the Automation Hub.
This will be the first change to make it possible.
With this, we can pass the required to publish into galaxy.
> Start polishing the Galaxy sanity check to publish the collection.

- os_migrate/plugins/module_utils/router.py
Previously routers were created without an external gateway interface,
this is now fixed. The interface is created on the network with the
same name as in the source cloud.
> Fix importing router external gateway

- tests/func/idempotence/all.yml
- tests/func/idempotence/router.yml
This patch adds a test to ensure idempotence for the router resource.
> Adds Router Idempotence Fuctional Test

- os_migrate/galaxy.yml
- os_migrate/plugins/module_utils/const.py
- os_migrate/tests/unit/test_serialization.py
- tests/func/data/validate_data_dir/invalid/networks-duplicate.yml
- tests/func/data/validate_data_dir/invalid/networks.yml
- tests/func/data/validate_data_dir/valid/networks.yml
> Prepare for 0.0.2 release to Galaxy

- os_migrate/plugins/module_utils/security_group_rule.py
- tests/func/idempotence/all.yml
- tests/func/idempotence/security_group_rule.yml
This patch adds a functional test to ensure security group rule idempotence.
> Adds Functional Test for Security Group Rule Idempotence

- tests/func/update/all.yml
- tests/func/update/network.yml
This patch adds the code to test the update of the network resource
and will ultimately include the fix for the failing update once
I find the root cause. :)
Note this patch is WIP.
> Adds Functional Test for Network Update

- tests/func/update/all.yml
- tests/func/update/network.yml
- tests/func/update/subnet.yml
This patch adds the code to test the update functionality of the
subnet resources.
Note: this patch is WIP
> Adds Update Functional Tests for Subnets

- tests/func/update/all.yml
- tests/func/update/security_group.yml
This patch adds a test to ensure the updates for security group
resources is working properly.
NOTE: WIP for a template failure in the assert.
> Adds Functional Update Test for Security Groups

- os_migrate/plugins/module_utils/network.py
- os_migrate/plugins/module_utils/reference.py
- os_migrate/plugins/module_utils/router.py
- os_migrate/plugins/module_utils/router_interface.py
- os_migrate/plugins/module_utils/security_group_rule.py
- os_migrate/plugins/module_utils/subnet.py
- os_migrate/plugins/modules/export_security_group_rules.py
- os_migrate/tests/unit/test_network.py
- os_migrate/tests/unit/test_reference.py
- os_migrate/tests/unit/test_router.py
- os_migrate/tests/unit/test_router_interface.py
- os_migrate/tests/unit/test_security_group_rule.py
- os_migrate/tests/unit/test_subnet.py
- tests/e2e/run.yml
- tests/func/run/router.yml
- tests/func/run/router_interface.yml
- tests/func/run/security_group_rule.yml
This implements fully qualified references in the whole of pre-workload migration. Workload migration has a slightly different codebase and is harder to test locally, so i will send its own pull request with fully qualified refs there.
Partially-fixes: #186
> Fully qualified references in pre-workload migration

- os_migrate/galaxy.yml
> Add Matthew into authors

- doc/devel/contributing.md
This patch adds information to help a potential contributor add
new roles or supporting code to the project.
> Adds Contribution Document

- doc/devel/README.md
Adds a link for the the contributing doc to the README.
> Adds Link For Contributing To Developer Doc

- os_migrate/plugins/module_utils/exc.py
- os_migrate/plugins/module_utils/image.py
- os_migrate/plugins/module_utils/workload_common.py
- os_migrate/plugins/modules/import_workload_cleanup.py
- os_migrate/plugins/modules/import_workload_export_volumes.py
- os_migrate/plugins/modules/import_workload_transfer_volumes.py
It seems like pylint got updated and our code started failing the
lint, this is now fixed.
> Fix pylint issues

- os_migrate/playbooks/import_images.yml
- os_migrate/plugins/module_utils/image.py
- os_migrate/plugins/modules/import_image.py
- os_migrate/roles/export_images/tasks/main.yml
- os_migrate/roles/import_images/defaults/main.yml
- os_migrate/roles/import_images/meta/main.yml
- os_migrate/roles/import_images/tasks/main.yml
- os_migrate/tests/sanity/ignore-2.9.txt
- os_migrate/tests/unit/test_image.py
- tests/e2e/run.yml
- tests/func/idempotence/all.yml
- tests/func/idempotence/image.yml
- tests/func/run/all.yml
- tests/func/run/image.yml
- tests/func/update/all.yml
- tests/func/update/image.yml
Implements Glance image import, includes idempotence and update tests.
> Implement Glance image import

- tests/func/idempotence/all.yml
- tests/func/idempotence/flavor.yml
- tests/func/idempotence/keypair.yml
This patch adds idempotence tests for the Nova Flavor and Keypair
resources.
> Adds Nova Idempotence Tests

- os_migrate/roles/export_images/README.md
- os_migrate/roles/import_images/README.md
Galaxy releasing fails without these.
> Add missing role readme files

- .github/workflows/consistency-functional.yml
There is a bug https://github.com/trilom/file-changes-action/issues/104
solved in latest version.
Currently the CI is broken.
> Dev: fix ci for file-changes-action

- tests/func/admin/clean/all.yml
- tests/func/admin/clean/flavor.yml
- tests/func/admin/idempotence/all.yml
- tests/func/admin/idempotence/flavor.yml
- tests/func/admin/run/flavor.yml
- tests/func/admin/seed/all.yml
- tests/func/admin/seed/flavor.yml
This includes the creation and migration
of flavors in the functinoal tests.
> Dev: Include flavor in functional tests

- os_migrate/galaxy.yml
- os_migrate/playbooks/deploy_conversion_hosts.yml
- os_migrate/plugins/module_utils/const.py
- os_migrate/plugins/module_utils/reference.py
- os_migrate/plugins/module_utils/server.py
- os_migrate/plugins/module_utils/workload_common.py
- tests/e2e/tenant/seed_workload.yml
- tests/e2e/test_as_tenant.yml
- tests/func/tenant/data/validate_data_dir/invalid/networks-duplicate.yml
- tests/func/tenant/data/validate_data_dir/invalid/networks.yml
- tests/func/tenant/data/validate_data_dir/valid/networks.yml
- toolbox/build/venv-requirements.txt
(see commits and their messages)
> Backport recent fixes in workload migration to stable/0.6, prepare release 0.6.2

- scripts/check_fqcn.py
- scripts/linters.sh
This patch enforce the policy to use the FQCN
across the collection.
> Dev: Lint fqcn

- Makefile
- scripts/build.sh
- toolbox/build/build.sh
- toolbox/build/venv-requirements-lower-bound.txt
- toolbox/run
> Dev: Introduce lower bound requirements + enablement in test mechanisms

- .github/workflows/consistency-functional.yml
- .gitignore
- Makefile
- tests/func/admin/clean/all.yml
- tests/func/admin/idempotence/all.yml
- tests/func/admin/run/all.yml
- tests/func/admin/seed/all.yml
- toolbox/build/build.sh
Installing the collection dependencies takes time, this PR
includes these dependencies in the os-migrate container image
so when they are installed if they are already include they will
be skipped.
> Dev: Include the galaxy collection dependencies in the container.

- .github/workflows/consistency-functional.yml
- tests/func/admin/clean/all.yml
- tests/func/admin/idempotence/all.yml
- tests/func/admin/run/all.yml
- tests/func/admin/seed/all.yml
This PR enables the functional tests related
to nova services.
> Dev: Enable nova services and functional tests

- os_migrate/plugins/module_utils/server.py
In the workloads YAML file we now write information about volume
attachments into the _info section. The actual volumes to migrate are
looked up again during the import phase, so this new serialized
information does not have any effect on the migration, but it can be
helpful when debugging.
> New: Add volume attachements info to workload exports

- docs/src/devel/contributing-code.rst
- docs/src/devel/design.rst
- docs/src/devel/dev-env-setup.rst
Edits to get the developer docs up to date and iron out some places.
> Dev: Developer docs update

- toolbox/run
This makes it possible to resolve DNS names in a VPN for example.
> Dev: Mount resolv.conf into toolbox

- os_migrate/roles/conversion_host_content/defaults/main.yml
- os_migrate/roles/conversion_host_content/tasks/rhel.yml
This commit adds the retry logic when
using RHSM in the conversion hosts.
> Dev: Add retry logic to RHSM

- .github/workflows/consistency-functional.yml
This commit enables the execution of our functional tests
also periodically.
> Chg: Run periodically the functional tests depending on DevStack

- toolbox/shell
- toolbox/vagrant-run
- toolbox/vagrant-shell
- toolbox/venv-shell
(see commit messages for description please)
> Dev: Fix vagrant container naming, remove deprecated toolbox shell scripts

- os_migrate/plugins/module_utils/image.py
Fixes issue #437
Signed-off-by: Yaniv Kaul <ykaul@redhat.com>
> Update comment in image.py

- docs/src/devel/dev-env-setup.rst
Adding new developer documentation for the end to end tests
detailing the prerequisites, config required, expected output
and optional tags/variables to pass when running.
> Dev: Add developer documentation for os-migrate e2e tests

- docs/src/user/variables-guide.rst
This commit adds the information for the ssh access using
password in the conversion hosts.
> Docs: Add password-based authentication variable docs.

- Makefile
- docs/src/user/install-from-galaxy.rst
- scripts/build.sh
- toolbox/build/build.sh
This commit helps to reduce the space burden
of the os-migrate container image.
> Dev: Reduce the container image size

- docs/src/user/migration-params-guide.rst
- os_migrate/plugins/module_utils/server.py
- os_migrate/plugins/modules/import_workload_export_volumes.py
- os_migrate/plugins/modules/import_workload_transfer_volumes.py
plus small refactors
(Described in commit messages.)
Resolves #444
> New: Ability to specify boot volume params when source VM has no boot volume

- Makefile
- docs/src/.gitignore
- docs/src/images/plantuml/workload-migration-sequence.plantuml
- docs/src/user/README.rst
- docs/src/user/how-it-works-workload-migration.rst
- tests/e2e/test_as_tenant.yml
- toolbox/build/build.sh
Also i'm piggy-backing a Dev commit into the pull request re tagging data seed tasks in tests, which came in handy for demo preparation.
> Oth: User documentation on the inner workings of workload migration

- os_migrate/plugins/module_utils/server.py
- os_migrate/tests/unit/test_server.py
dst_prerequisites_errorsclass method is used to validate prerequisites
before migrating workloads but the parent class dst_prerequisites_errors
does not validate keypairs exist in destination cloud. To do this we do
a lookup to see if keypair name exists and append to errors list if not
> Fix: Validate keypairs exist in destination cloud before migrating workload

- os_migrate/playbooks/deploy_conversion_hosts.yml
- os_migrate/roles/conversion_host/tasks/link_prepare.yml
(Described in commit messages.)
> Fix/Chg: Conversion host performance improvements

- docs/src/user/install-from-galaxy.rst
Discussed at https://github.com/os-migrate/os-migrate/issues/489
> Dev: Docs mention that Ansible must run on Python 3

- os_migrate/plugins/module_utils/const.py
- os_migrate/plugins/module_utils/image.py
- os_migrate/plugins/module_utils/keypair.py
- os_migrate/plugins/module_utils/network.py
- os_migrate/plugins/module_utils/project.py
- os_migrate/plugins/module_utils/reference.py
- os_migrate/plugins/module_utils/resource.py
- os_migrate/plugins/module_utils/router.py
- os_migrate/plugins/module_utils/router_interface.py
- os_migrate/plugins/module_utils/security_group_rule.py
- os_migrate/plugins/module_utils/server.py
- os_migrate/plugins/module_utils/server_floating_ip.py
- os_migrate/plugins/module_utils/server_port.py
- os_migrate/plugins/module_utils/subnet.py
- os_migrate/plugins/module_utils/user.py
- os_migrate/tests/unit/test_resource.py
- os_migrate/tests/unit/test_server.py
> Remove filters from _refs_from_ser, create constant for %auth%

- .github/workflows/consistency-functional.yml
This commit adds the correct name for the new
MySQL client.
> Dev: fix the MySQL client package dependency

- .github/workflows/consistency-functional.yml
This patch install again the MySQL client
package.
> dev: MySQL client is broken again in 18.04

- os_migrate/plugins/modules/import_workload_transfer_volumes.py
Resolves: https://github.com/os-migrate/os-migrate/issues/528
> dev: Fix example of block_device_mapping structure

- os_migrate/plugins/module_utils/network.py
- os_migrate/tests/unit/test_network.py
- Tested in unit and passes, ended up commenting out - not sure if this would even require its own testcase of any sorts?
> new: skip serialization if dns_domain is false

- os_migrate/roles/prelude_common/tasks/main.yml
- os_migrate/roles/prelude_common/templates/clouds.yaml.j2
Yaml format for clouds file is a little weird - will play with indents. 
```
clouds:
src:
auth: auth_url: http://192.168.122.4/identity
password: password
project_domain_id: default
project_name: demo
user_domain_id: default
username: demo
region_name: RegionOne
dst:
auth: auth_url: http://192.168.122.4/identity
password: password
project_domain_id: default
project_name: alt_demo
user_domain_id: default
username: alt_demo_member
region_name: RegionOne
```
> new: Write auth config to clouds.yaml

- os_migrate/plugins/module_utils/server_port.py
- os_migrate/tests/unit/test_server_port.py
We export server port info from Neutron API, because it gives more
information about the port. However, querying ports from Neutron seems
to give a somewhat random order of the ports.
Now we still export the same Neutron info about ports, but we sort
them based on the order in which the VM IP addresses appear in
OpenStack SDK's 'compute.get_server' return value.
This approach cannot guarantee that the original order of NICs is
preserved during migration (Nova does not guarantee NIC ordering [1]),
but it makes it more likely that the NIC order will be preserved
during migration.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1798126
> new: Sort exported server ports as they appear in Nova API

- .github/workflows/consistency-functional.yml
@jistr: "This is an attempt to fix the following error in CI:
The following packages have unmet dependencies:
postgresql-server-dev-all : Depends: postgresql-common (= 238) but 246.pgdg22.04+1 is to be installed
E: Unable to correct problems, you have held broken packages."
> dev: functional ci patch

- toolbox/vagrant/vagrant-config.yml
- toolbox/vagrant/vagrant-up
https://github.com/openstack/devstack/blob/69d71cfdf9c24d48fbea366714f4595cbd120723/stack.sh#L232
Signed-off-by: Fabricio Aguiar <fabricio.aguiar@gmail.com>
> dev: Update Devstack Vagrant base image to Fedora 36

- os_migrate/plugins/module_utils/workload_common.py
This adds a `remove_lockfiles` and `check_process` method to the `use_locks` decorator to handle responses to waiting for lockfile releases within the conversion hosts. https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=16007&view=detail&selectedIssue=OSP-13078&quickFilter=101301
> dev: lockfile patch for use_lock process

- os_migrate/plugins/module_utils/server.py
- os_migrate/plugins/module_utils/server_port.py
- os_migrate/tests/unit/test_server_port.py
- tests/e2e/tasks/tenant/clean_empty_device_owners.yml
- tests/e2e/tasks/tenant/clean_workload.yml
- tests/e2e/tasks/tenant/clean_workload_existing_neutron_ports.yml
- tests/e2e/tasks/tenant/run_workload.yml
- tests/e2e/test_as_tenant.yml
This PR aims to cover https://issues.redhat.com/browse/OSP-18661 and will include a fresh deployment to ansible galaxy.
> new: port binding & creation via neutron api

- os_migrate/playbooks/import_networks.yml
- scripts/build.sh
Issue references #607 + fix to build/functional steps
> dev!: patch cachecontrol one & import_networks update

- os_migrate/plugins/module_utils/workload_common.py
Seems to be an issue with authentication within clouds, https://access.redhat.com/support/cases/#/case/03479904. Investigating issue,
> dev: lockfile bug for cleanup

- os_migrate/roles/import_workloads/tasks/main.yml
- tests/e2e/tasks/common/test_seeded_workloads.yml
- tests/e2e/tasks/tenant/clean_workload.yml
- tests/e2e/tasks/tenant/multi_volume_migration/seed_workload.yml
- tests/e2e/test_as_tenant.yml
Covers issue here, https://issues.redhat.com/browse/OSPRH-1981
> dev: testing migration of multi volume state for osm_server

- .ansible-lint
- .github/workflows/ansible-lint.yml
- .github/workflows/consistency-functional.yml
- .github/workflows/container-image-build.yml
- .github/workflows/docs-build-pr.yml
- .github/workflows/docs-build.yml
Add ansible-lint job for Ansible certification.
> dev: add ansible-lint github workflow

- .github/workflows/build-aee.yml
- Makefile
Since CentOS Stream 10 doesn't provide the `shyaml` tool, we are installing it via `pip`
> Fixed the installation of the `shyaml` tool
