os-migrate/os-migrate

doc/contributing.md
toolbox/build/build.sh
toolbox/run
toolbox/vagrant-run

`make toolbox-clean toolbox-build` is required to get the new image with `/.os-migrate-toolbox` file present.
Tested:
```
$ ./toolbox/shell 
[root@axon os_migrate]# ./toolbox/run echo test
ERROR: You're already within an os-migrate toolbox container.
Calls to toolbox shouldn't be nested.
[root@axon os_migrate]# ./toolbox/vagrant-shell 
ERROR: You're already within an os-migrate toolbox container.
Calls to toolbox shouldn't be nested.
[root@axon os_migrate]# 
```

Prevent nesting of toolbox commands

---

.github/workflows/devstack.yml

We were hitting weird issues in filesystem ownership [1] which failed
devstack install. Making sure the ownership is correct seems to fix
the problems.
[1] https://ubuntuforums.org/showthread.php?t=2406453

Fix filesystem ownership in CI

---

Makefile
os_migrate/plugins/module_utils/const.py
os_migrate/plugins/module_utils/filesystem.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/serialization.py
os_migrate/plugins/modules/export_network.py
os_migrate/roles/export_networks/tasks/main.yml
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_filesystem.py
os_migrate/tests/unit/test_network.py
os_migrate/tests/unit/test_serialization.py
os_migrate/tests/unit/utils.py
tests/func/run/network.yml
tests/func/seed/network.yml

This adds serialization and resource file read/write basics, and adds
rudimentary network exporting.
We may further think whether using some classes for our structures
makes sense, or if just plain dict/list structures are good enough (my
initial approach in this commit). Given that Python is a dynamic
language, we won't get any compile time validation even if we do add
classes/structures for the data, and any errors will pop up at runtime
either way. This already manifested in dealing with the openstacksdk's
Network class -- even though it's a class, it didn't feel like we're
getting many benefits from it over a plain dict, it is very free-form,
see serialization method in network.py.

Add serialization basics and network exporting

---

os_migrate/playbooks/import_networks.yml
os_migrate/plugins/module_utils/exc.py
os_migrate/plugins/module_utils/filesystem.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/serialization.py
os_migrate/plugins/modules/import_network.py
os_migrate/plugins/modules/read_resources.py
os_migrate/roles/import_networks/tasks/main.yml
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_filesystem.py
os_migrate/tests/unit/test_network.py
os_migrate/tests/unit/test_serialization.py
tests/func/run/network.yml
toolbox/build/venv-requirements.txt

The import_networks playbook and role, and import_network module are
for importing networks specifically.
The read_resources module is meant for all importing in general. It
loads the resource YAML file structure into an Ansible variable so
that individual resources can be iterated on inside the roles.
Small deserialization utility functions are added too, for
transforming serialized data into parameters for OpenStack SDK when
creating/updating resources.
There is a block in functional tests that isn't very nice but it can
be fully removed once we implement name-based filtering on export:
https://github.com/os-migrate/os-migrate/issues/22
The PR closes #14.

Resource file reading and networks import

---

Makefile
os_migrate/plugins/module_utils/const.py
scripts/build.sh

Initially i wanted to just load the collection manifest from const.py,
but it's not possible, more details at [1].
Our next best shot is probably to auto-update const.py constant
OS_MIGRATE_VERSION each time we build the collection, which is what
this commit implements.
[1] https://github.com/os-migrate/os-migrate/pull/28
Closes #12

Update version in const.py based on galaxy.yml when building the collection

---

os_migrate/plugins/module_utils/network.py
os_migrate/plugins/modules/import_network.py
os_migrate/tests/unit/test_network.py
tests/func/idempotence/network.yml

Depends on PRs #23, #27, #31 
For idempotence of imports we largely have all the pieces, all that
needs to be done is to serialize the existing network into our format
and compare if the resulting 'params' are the same as the ones
provided to the import_network module.
Crucial is looking at 'params' only and not 'info', as 'params'
contain the important network parameters that are meant to be
migrated, while 'info' contains non-migratable info, e.g. the
network's UUID.

Import idempotence

---

os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/reference.py
os_migrate/plugins/module_utils/serialization.py
os_migrate/plugins/modules/export_network.py
os_migrate/plugins/modules/import_network.py
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_network.py
os_migrate/tests/unit/test_reference.py
os_migrate/tests/unit/test_serialization.py
tests/func/idempotence/network.yml

Depends on #32 . Closes #37.
Converting to/from name-based references (ID-based references are not transferable information across clouds).

References

---

os_migrate/plugins/module_utils/network.py

Fix a case of copypasta in network_refs_from_ser function.
Remove the TODOs related to the Network refs. Originally i wanted to
load also project_name and subnet_names list, but those are not
necessary for importing under current OS-Migrate assumptions, and
fetching this information in network_refs_from_sdk and
network_refs_from_ser would slow down the import/export with
unnecessary API requests. For now let's assume this info does not need
to be queried, we can re-evaluatethe decision if we get any hints that
this info would be useful.

Fix qos_policy ref in Network and remove TODOs

---

Makefile
tests/func/clean/all.yml
tests/func/global/prep.yml
tests/func/idempotence/all.yml
tests/func/run/all.yml
tests/func/seed/all.yml
tests/func/test_network.yml

To run subset of functional tests, the current pattern was to create a
full playbook which would only include the desired parts.
An alternative pattern might be to use --skip-tags or --tags with the
test_all.yml playbook. This might allow better mix-and-match execution
for particular test environments and developer scenarios.
Due to env vars not being automatically passed into the toolbox
container, currently there are two ways to test this approach e.g. by
skipping the network tests:
./toolbox/shell
FUNC_TEST_ARGS='--skip-tags test_network' make test-func
and
./toolbox/run bash -c "FUNC_TEST_ARGS='--skip-tags test_network' make test-func"
The 2nd case perhaps deserves some improvement (list of env vars we
want to detect and pass into toolbox container automatically?) but
that's beyond …

Use tags in functional tests instead of separate playbooks

---

toolbox/build/build.sh

I thought i was pasting just vagrant-libvirt package list but in fact
pasted full Tmit build package list. We don't need the Rust bits in
OS-Migrate.

Remove Tmit PoC build requirements

---

toolbox/build/build.sh

We install a bunch of (latest) RPMs but until now we didn't update the
others. This could result in a mixture of RPMs that has never been
tested together in Fedora. Let's update packages before installing
additional ones.

Make sure toolbox container RPMs are up-to-date when building

---

os_migrate/plugins/module_utils/const.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/serialization.py
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_filesystem.py
os_migrate/tests/unit/test_network.py
os_migrate/tests/unit/test_serialization.py

Work on Security Groups spawned a discussion about some
conventions. This patch performs following adaptation:
* Use '_info' instead of 'info' for resource properties which are
irrelevant for importing and idempotence checks. This should further
reduce a chance of conflict with some real property and allow us to
ignore any '_info' *also in nested dicts* when importing / checking
idempotence.
* Better namespacing for Network type
serialization. 'openstack.network.Network' rather than
'openstack.network'.

Adapt conventions based on Security Groups discussion

---

os_migrate/plugins/module_utils/filesystem.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/reference.py
os_migrate/plugins/module_utils/serialization.py

Documents what our functions (especially the reusable ones that are
intended to be shared) should do.
Since Pydoc is a free-form format, i went for very simple way of
describing the functions, trying to maximize the information provided
per characters typed and limit rigid boilerplate. This should help us
be diligent about documenting the functions by making documentation
not much pain to write :).

Document reusable module_utils functions and network functions

---

os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/serialization.py
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_serialization.py

The resource_needs_update function should be generically usable on all
our resources to check whether some resource is in target state or
needs update (= idempotence checks). It is right away plugged into the
check method for Network.

Implement generic idempotence checker

---

os_migrate/plugins/module_utils/serialization.py
os_migrate/tests/unit/test_serialization.py

When two resources have the same type but their names are undefined,
we should not consider them the same. This is now the case after a
copypasta typo is fixed, and tests are added to verify correct
behavior.

Fix checker of resource sameness, add tests for it

---

.github/workflows/functional-all.yml
.github/workflows/unit-all.yml
Makefile
toolbox/build/build.sh

We don't need Vagrant in CI and it pulls a lot of deps, skipping its
installation in CI should speed up the jobs.
Closes #24

Do not build container with Vagrant in CI

---

os_migrate/plugins/filter/stringfilter.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/serialization.py
os_migrate/plugins/modules/export_network.py
os_migrate/roles/export_networks/tasks/main.yml
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_filesystem.py
os_migrate/tests/unit/test_network.py
os_migrate/tests/unit/test_serialization.py
os_migrate/tests/unit/test_stringfilter.py

This change is fueled by work on validations. We have essentially 2
options there:
* Export all resources including ones with empty name and duplicate
names. Then run validatiton on the exported files. This requires
that resources are iterated over for export by ID and not by name.
This is nicer because the files can be perhaps edited by hand to
amend the naming on destination cloud without forcing name changes
on source cloud. Validation can be re-ran arbitrarily on the files
to iterate forward.
* Validate the state in the source cloud to verify whether export can
be ran, and change the state in the source cloud until unique naming
is achieved. Then run export.
This is less nice because amendments of the source cloud are
necessary before an export can be performed.
To achieve the former …

Allow exporting non-uniquely named resource sets

---

os_migrate/plugins/module_utils/exc.py
os_migrate/plugins/module_utils/filesystem.py
os_migrate/tests/unit/test_filesystem.py

Currently we do not guarantee any backward/forward compatibility in
serialized files. Using different version of OS-Migrate between export
and import isn't supported. Should users get to a situation where
differing versions are needed between export and import, they will
have to investigate the risks and e.g. `sed` the version in files to
the expected one. We're defaulting to being defensive here.
I was thinking whether this could go into validations as one of the
validation errors, but in fact if the versions are different, we
cannot even guarantee that the validations will work correctly, so
let's be careful and just raise a clear exception right away.
Closes https://github.com/os-migrate/os-migrate/issues/20

Assert correct os_migrate_version when loading files

---

os_migrate/galaxy.yml
os_migrate/playbooks/export_security_group_rules.yml
os_migrate/playbooks/export_security_groups.yml
os_migrate/plugins/module_utils/const.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/modules/export_security_group.py
os_migrate/plugins/modules/export_security_group_rules.py
os_migrate/plugins/modules/os_security_group_rules_info.py
os_migrate/plugins/modules/os_security_groups_info.py
os_migrate/roles/export_security_group_rules/defaults/main.yml
os_migrate/roles/export_security_group_rules/tasks/main.yml
os_migrate/roles/export_security_groups/defaults/main.yml
os_migrate/roles/export_security_groups/tasks/main.yml
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_security_group.py
os_migrate/tests/unit/test_security_group_rule.py

This patch exports the current deployed security groups into
the yaml os-migrate format.

Adding the export security groups

---

toolbox/vagrant/ansible/roles/devstack/tasks/config.yml
toolbox/vagrant/vagrant-config.yml
toolbox/vagrant/vagrant-up

Fedora 29 is no longer supported.
Closes https://github.com/os-migrate/os-migrate/issues/74
Closes https://github.com/os-migrate/os-migrate/issues/65

Update Vagrant-Devstack setup to Fedora 30

---

os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/reference.py
os_migrate/plugins/modules/export_security_group_rules.py
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_security_group_rule.py

This commit adds the parameter security_group_name
to the params section.
Closes: #79

Including matching id by name for the security group name on rules param section

---

os_migrate/playbooks/validate_data_dir.yml
os_migrate/plugins/module_utils/validation.py
os_migrate/plugins/modules/validate_resource_files.py
os_migrate/roles/import_networks/defaults/main.yml
os_migrate/roles/import_networks/tasks/main.yml
os_migrate/roles/validate_data_dir/tasks/main.yml
os_migrate/tests/unit/test_validation.py
tests/func/data/validate_data_dir/invalid/networks-duplicate.yml
tests/func/data/validate_data_dir/invalid/networks.yml
tests/func/data/validate_data_dir/valid/networks.yml
tests/func/independent/all.yml
tests/func/independent/validate_data_dir.yml
tests/func/test_all.yml

This adds validation of resource files. Unique resource naming in
ensured per resource type. Multiple resource files can be fed into the
validation, so if someone had a resource file setup where resources of
the same type are spread across multiple files, the names would still
get validated properly.
Validation can currently be executed in 2 ways:
* After loading resources, before importing them (can be disabled by a
boolean flag).
* Independently on all resources in a directory via validate_data_dir
playbook.
Closes #58 .

Add validation of unique resource naming

---

toolbox/vagrant-run

I was considering several options how to solve the issue of incorrect
$HOME ownership in containers:
* Give the user sudo rights to do the chown in entrypoint. Bad mainly
because we don't know which user we'll run as when creating the
container image, and for sudo to work in a container we also need to
mount in /etc/shadow (even when using NOPASSWD sudo).
* Launch the container as root, perform chown in its entrypoint, and
then `su` to another user (we'd pass it in via env variable) to run
the real command. Better than previous but reimplementing the
`--user` argument of `podman run` via an env variable and custom
entrypoint still feels somewhat suboptimal, especially if Vagrant is
not the only use case for the os_migrate_toolbox image.
* First create the container without starting it, …

Correct $HOME ownership in vagrant-run and vagrant-shell

---

toolbox/Dockerfile

We had several CI issues related to errors when pulling the
container image from registry.fedoraproject.org
Maybe we wont hit this anymore if we use Docker Hub.
Also, the image shuold be exactly the same.

registry.fedoraproject.org consistently fails on pulling images

---

os_migrate/playbooks/export_routers.yml
os_migrate/plugins/module_utils/const.py
os_migrate/plugins/module_utils/reference.py
os_migrate/plugins/module_utils/router.py
os_migrate/plugins/modules/export_router.py
os_migrate/plugins/modules/os_routers_info.py
os_migrate/roles/export_routers/defaults/main.yml
os_migrate/roles/export_routers/tasks/main.yml
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_router.py
tests/func/clean/all.yml
tests/func/clean/router.yml
tests/func/run/all.yml
tests/func/run/router.yml
tests/func/seed/all.yml
tests/func/seed/router.yml

Note that this doesn't export router's interfaces on private subnets,
they will have to be exported/imported via a separate resource.
Closes #70

Implement Router export

---

tests/func/clean/all.yml
tests/func/idempotence/all.yml
tests/func/run/all.yml
tests/func/seed/all.yml

Now one can run this to run only Network tests for example:
./toolbox/run bash -c "FUNC_TEST_ARGS='--tags test_network' make test-func"
or Network + Subnet tests:
./toolbox/run bash -c "FUNC_TEST_ARGS='--tags test_network,test_subnet' make test-func"
Special new use case is:
./toolbox/run bash -c "FUNC_TEST_ARGS='--tags test_clean' make test-func"
which will only clean up the test data from the named clouds.

Allow running functional tests more individually

---

toolbox/vagrant-run

The TTY-related options passed to create vs. start are not perfect
substitutes of each other.
* When calling `start`, we want to always pass `-a` even when not in
interactive shell, simply to avoid launching the container in
background (`podman start` ~= `podman run -d`; `podman start -a` ~=
`podman run`).
* There is no `-t` equivalent for `podman start`. It looks like we
need to decide on allocating pseudo-TTY in `podman create`.
* I'm not 100% sure on the `-i` behavior but from docs it looks like
we either want to pass it to both or neither.

Fix podman's TTY-related options in vagrant-run

---

os_migrate/plugins/module_utils/filesystem.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/resource.py
os_migrate/plugins/module_utils/serialization.py
os_migrate/plugins/modules/export_network.py
os_migrate/plugins/modules/import_network.py
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_network.py
os_migrate/tests/unit/test_resource.py

We created a Resource class as the base class for all our exported
resources. It improves the DRYness of our overall code and is suitable
for both export and import. It uses method composition internally so
that it can be easily "disconnected from network" for purposes of unit
testing.
The common interfaces are now backwards compatible, e.g. the
add_or_replace method for exporting resources now accepts both direct
resource data or an instance of Resource.
Co-Authored-By: Ryan Brady <rbrady@redhat.com>
Closes: #83

Resource class

---

scripts/linters.sh

Ansible-lint is the slowest linter, running it last should speed up
catching Python and YAML lint issues via `test-fast` target.

Run ansible-lint as the last of the linters

---

scripts/linters.sh

These resource files are generated in tests via YAML dumper and they
don't pass the lint check on indentation :).
Also reformat the linters.sh file to make the commands a bit easier to
read.

Do not lint YAML files in ./tests/func/tmpdata

---

os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/resource.py
os_migrate/tests/unit/test_resource.py

By extracting the find/create/update calls for the underlying SDK
object, we can provide a default implementation for the
create_or_update method on Resource. Subclasses can either provide the
find/create/update mini-methods and reuse the create_or_update logic,
or override the create_or_update method fully.

 Default implementation for Resource.create_or_update

---

os_migrate/plugins/module_utils/subnet.py
os_migrate/tests/unit/test_subnet.py

During the idempotency testing, the subnet update calls to the API
failed for ip_version and network_id.  These parameters are accepted
for the create, but not the update.  Sorting the allocation_pools and
dns_nameservers migtigated the condistion that caused this error.

Fix Subnet Update

---

os_migrate/plugins/module_utils/security_group.py
os_migrate/plugins/modules/export_security_group.py
os_migrate/plugins/modules/import_security_group.py
os_migrate/tests/unit/fixtures.py
os_migrate/tests/unit/test_security_group.py

This is the second part of the OOP refactor, by doing the split first the complexity of the change is reduced a lot.

OOP sec group

---

os_migrate/plugins/module_utils/resource.py
os_migrate/plugins/module_utils/subnet.py
os_migrate/tests/unit/test_subnet.py

The last param that must be sorted for import idempotence to work is
'host_routes'. It's a list of dicts so it needs a list of keys to look
at in each dict. The list-of-dicts sorting is implemented in Resource
class to be reusable.
Closes #140

Fix subnet import idempotence

---

doc/devel/design.md
doc/devel/dev-env-setup.md

The dev docs for running functional tests went out of date as we
changed auth mechanism and as we changed how to run a subset of
functional tests. They are now updated to current workflows.
Also slight edit has been made to the design doc now that we've made
some implementation decisions where previously there was uncertainty.

Update dev docs

---

os_migrate/plugins/module_utils/resource.py
os_migrate/tests/unit/test_resource.py

Intermittently, the subnet import functional tests fail for ip_version
or network_id attributes.  This patch removes the ip_version and
network_id from the update args.
closes #140

Fixes Subnet Update

---

scripts/build.sh

This might hit us in our dev envs, we should push a fix for this asap.
Closes: #156

Do not ls, use always current version as latest

---

doc/devel/dev-env-setup.md
tests/func/test_all.yml

Previously it was possible to skip cleanup via `--skip-tags
test_clean`, but that would affect cleanup both before and after
testing. It is now possible to skip the cleanup only after testing,
with `--skip-tags test_clean_after`.

Allow skipping func test cleanup only after testing

---

os_migrate/plugins/module_utils/security_group_rule.py
os_migrate/tests/unit/test_security_group_rule.py

This is a fundamental property of the rule, specifies whether the rule
applies to IPv4 or IPv6 traffic.

Save ether_type for security group rules

---

scripts/publish.sh

E.g. if shyaml is missing, the releasing will fail with a weird
error. In toolbox, we have all the releasing dependencies.

Make sure releasing is done from toolbox container

---

os_migrate/plugins/module_utils/workload_common.py
os_migrate/plugins/modules/import_workload.py
os_migrate/plugins/modules/import_workload_prelim.py
os_migrate/roles/import_workloads/tasks/main.yml
os_migrate/roles/import_workloads/tasks/workload.yml
os_migrate/tests/sanity/ignore-2.9.txt

Split the workload migration tasks into two stages, so that the first stage can display log locations before going silent for the bulk data transfer. It ends up looking like this:
```
TASK [import_workloads : preliminary setup for workload import] ************************************************************
changed: [localhost]
TASK [import_workloads : debug] ********************************************************************************************
ok: [localhost] => {
"msg": [
"second-migration-vm local stdin/stderr: /home/migrate/lab-migrate-data/second-migration-vm.log",
"second-migration-vm log file: cloud-user@10.19.2.137:/tmp/v2v-6aHvCz/log/uci/virt-v2v-wrapper.log",
"second-migration-vm progress state file: cloud-user@10.19.2.137:/tmp/v2v-6aHvCz/lib/uci/state.json"
]
}
TASK …
```

Allow better workload debug logging and progress tracking

---

os_migrate/plugins/module_utils/router_interface.py
tests/func/idempotence/all.yml
tests/func/idempotence/router_interface.yml

This patch adds a test to ensure router interface idempotence.

Adds test for Router Interface idempotence

---

doc/user/README.md
os_migrate/README.md

This patch adds more data to the repo README and updates the
the user doc to remove clouds.yml info and replace it with
the newer auth vars.
* Note this patch is still WIP as I'm trying to figure out the
best way to adapt the blog post to the user docs as well.

Adds additional user docs

---

os_migrate/roles/export_networks/README.md
os_migrate/roles/export_router_interfaces/README.md
os_migrate/roles/export_routers/README.md
os_migrate/roles/export_security_group_rules/README.md
os_migrate/roles/export_security_groups/README.md
os_migrate/roles/export_subnets/README.md
os_migrate/roles/export_workloads/README.md
os_migrate/roles/import_networks/README.md
os_migrate/roles/import_router_interfaces/README.md
os_migrate/roles/import_routers/README.md
os_migrate/roles/import_security_group_rules/README.md
os_migrate/roles/import_security_groups/README.md
os_migrate/roles/import_subnets/README.md
os_migrate/roles/import_workloads/README.md
os_migrate/roles/prelude_dst/README.md
os_migrate/roles/prelude_src/README.md
os_migrate/roles/validate_data_dir/README.md

It looks like this is now required, otherwise the Galaxy publish
script fails with:
ERROR! Galaxy import process failed: No role readme found. (Code: None)

Add readme files to all roles, pointing to user docs

---

os_migrate/roles/export_router_interfaces/defaults/main.yml

Just a missing default.
Closes https://github.com/os-migrate/os-migrate/issues/201

Fix exporting router interfaces when router name filter is undefined

---

os_migrate/roles/export_router_interfaces/defaults/main.yml

Just a missing default.
Closes https://github.com/os-migrate/os-migrate/issues/201
(cherry picked from commit fc81f87d147980aae45f205959d42628885f4b36)

[stable/0.3] Fix exporting router interfaces when router name filter is undefined

---

Makefile
os_migrate/localhost_inventory.yml
os_migrate/plugins/module_utils/server.py
os_migrate/plugins/modules/export_workload.py
os_migrate/plugins/modules/import_workload_export_volumes.py
os_migrate/tests/unit/test_workload.py
tests/e2e/seed.yml

In CI we're hitting this error:
File "/tmp/ansible_os_migrate.os_migrate.import_workload_export_volumes_payload_4g3ps56s/ansible_os_migrate.os_migrate.import_workload_export_volumes_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_export_volumes.py", line 364, in _detach_data_volumes_from_source
AttributeError: 'NoneType' object has no attribute 'id'
Looks like the call to create snapshot returns None. We'll try moving
the timeout into the call itself and using wait=True.

Fix workload migration pt.1

---

os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/resource.py
os_migrate/plugins/module_utils/router.py
os_migrate/plugins/module_utils/security_group.py
os_migrate/plugins/module_utils/subnet.py

For the resources that support updating, the code previously called
the update sending the resource name causing the update to fail
from the corresponding API with a "BadRequest" error.  This patch
updates the code to use the instance of the resource itself when
calling the associated update method.
Co-authored-by: Jiri Stransky <jistr@redhat.com>

Fix Resource Updates

---

tests/func/update/network.yml
tests/func/update/router.yml
tests/func/update/security_group.yml
tests/func/update/subnet.yml

The lineinfile module only makes sure one line is present. So after it
does its replacement in one spot, it stops replacing. Due to random
order of subnets in the file, it sometimes replaces the description of
the wrong subnet, resulting in intermittent failures. To make the
tests work, we simply replace descriptions of both subnets in the func
test, and then we check only one.
To keep tests consistent, use 'replace' instead of 'lineinfile' module
in other tests too.

Fix subnet update test

---

os_migrate/galaxy.yml
os_migrate/plugins/module_utils/const.py
tests/func/data/validate_data_dir/invalid/networks-duplicate.yml
tests/func/data/validate_data_dir/invalid/networks.yml
tests/func/data/validate_data_dir/valid/networks.yml

Mainly utilizes a new workload migration approach with new conversion
host and conversion host deployment/deletion playbooks.

Prepare release 0.4.0

---

doc/user/README.md
doc/user/install-from-galaxy.md

Remove the walkthrough-like part of the root user readme, we have a
specific Walkthrough doc now. Make the main readme a link directory.

Restructure user documentation landing page

---

doc/user/walkthrough.md

When the walkthrough doc was merged, the URIs for the images were
incorrect and the images were not displayed for users.  This patch
fixes the URIs for the images to the correct path and removed an
erroneous TODO comment left in the previous version.

Fixes Walkthrough Images

---

.github/workflows/consistency-functional.yml
.gitignore
Makefile
os_migrate/playbooks/export_images.yml
os_migrate/plugins/module_utils/const.py
os_migrate/plugins/module_utils/image.py
os_migrate/plugins/module_utils/reference.py
os_migrate/plugins/modules/export_image_blob.py
os_migrate/plugins/modules/export_image_meta.py
os_migrate/roles/export_images/defaults/main.yml
os_migrate/roles/export_images/meta/main.yml
os_migrate/roles/export_images/tasks/main.yml
os_migrate/tests/sanity/ignore-2.9.txt
os_migrate/tests/unit/test_image.py
scripts/linters.sh
tests/e2e/clean.yml
tests/e2e/prep.yml
tests/e2e/run.yml
tests/e2e/seed.yml
tests/func/clean/all.yml
tests/func/clean/image.yml
tests/func/global/prep.yml
tests/func/idempotence/network.yml
tests/func/run/all.yml
tests/func/run/image.yml
tests/func/seed/all.yml
tests/func/seed/image.yml

Since Glance images contain binary data, the export is done via two
modules:
* export_image_meta -- exports image metadata (YAML file)
* export_image_blob -- exports image binary data
The export of binary data is optional. This split between metadata and
data exporting should leave us an open door towards migrating images
in a direct way between clouds (e.g. via conversion hosts) rather than
via the migrator host.

Export of Glance images

---

os_migrate/playbooks/export_flavors.yml
os_migrate/playbooks/import_flavors.yml
os_migrate/plugins/module_utils/const.py
os_migrate/plugins/module_utils/flavor.py
os_migrate/plugins/modules/export_flavor.py
os_migrate/plugins/modules/import_flavor.py
os_migrate/roles/export_flavors/README.md
os_migrate/roles/export_flavors/defaults/main.yml
os_migrate/roles/export_flavors/meta/main.yml
os_migrate/roles/export_flavors/tasks/main.yml
os_migrate/roles/import_flavors/README.md
os_migrate/roles/import_flavors/defaults/main.yml
os_migrate/roles/import_flavors/meta/main.yml
os_migrate/roles/import_flavors/tasks/main.yml
os_migrate/tests/sanity/ignore-2.9.txt
os_migrate/tests/unit/test_flavor.py
tests/func/run/all.yml
tests/func/run/flavor.yml

This patch adds import and export roles, supporting files and tests
for migrating Nova Flavors between clouds.

Adds Import and Export Roles for Nova Flavors

---

doc/user/walkthrough.md

This makes walkthrough doc up to date and generally into a better
shape. Some notable changes:
* Prerequisites section regarding authentication and parameters which
are used for both pre-workload and workload migration is
consolidated and moved at the beginning of the doc.
* Nesting of headlines is fixed.
* Removed mentions RH OSP.
* Updated conversion host deployment to use the playbook instead of
manual wiring instructions.
* Updated the workload migration process to the new one which runs on
plain CentOS and doesn't require VDDK.
* Command shortcuts.

Walkthrough doc updates and formatting fixes

---

os_migrate/plugins/modules/import_workload_create_instance.py
tests/e2e/seed.yml

The nics parameter is not documented in the upstream
docs, also there is no way in inject the MAC address,
or assign the floating IP when executing create_server
This should be fixed by creating a port and assign it
to the node before is created.

Include the fixed IP when restoring the server

---

os_migrate/roles/export_images/tasks/main.yml

This kind of filtering is standard for our other resources, but for
Glance images it was missing due to Glance API lack of functionality
which translates into lack of functionality in the os_image_info
Ansible module. The filtering is done explicitly in the playbook now.

Filter exported images by the currently authenticated project

---

os_migrate/playbooks/deploy_conversion_hosts.yml
os_migrate/roles/conversion_host/defaults/main.yml

DNS nameservers is a parameter for conversion subnet where it makes
sense to allow different values between src/dst clouds.

Allow setting conversion subnet DNS separately for src/dst

---

Makefile
os_migrate/plugins/modules/import_workload_prelim.py
os_migrate/roles/conversion_host/tasks/conv_hosts_inventory.yml
os_migrate/roles/conversion_host/tasks/link_prepare.yml
tests/e2e/common/prep.yml
tests/e2e/tenant/clean_pre_workload.yml
tests/e2e/tenant/clean_workload.yml
tests/e2e/tenant/run_pre_workload.yml
tests/e2e/tenant/run_workload.yml
tests/e2e/tenant/seed_pre_workload.yml
tests/e2e/tenant/seed_workload.yml
tests/e2e/test_as_tenant.yml

Currently running e2e tests does all this: deploy conversion hosts,
seed pre-workload resources, then workload resources, then migrate
pre-workload, then migrate workload, then clean everything up.
For working on workload migration, it would be great if we could leave
conversion hosts and pre-workload resources in place between test
runs, and only cycle seed-migrate-clean on the actual workload. This
is now implemented, but the default test run remains unchanged.
First i can just run everything without cleaning up:
```
./toolbox/run bash -c "E2E_TEST_ARGS='--skip-tags test_clean_after -e test_clean_conversion_hosts_after=false' make test-e2e-tenant"
```
And then i can run workload tests specifically, which will auto-clean
before and after, but only the workload parts:
```
./toolbox/run …
```

Speed up dev iteration on e2e tests

---

os_migrate/plugins/modules/import_workload_transfer_volumes.py

The EAGAIN error code is used when polling, meaning there's no data to
read right now but it should be tried again later. Instead of trying
right away, sleep for a second. This will prevent Ansible from eating
100% CPU on the migrator machine.
Closes: https://github.com/os-migrate/os-migrate/issues/280

Stop busy-looping during volume transfer (fix for 100% CPU usage)

---

Makefile

we need to make sure the V2s2 manifest is stored in each image, if not, when we pull the container image the v2s2 format type will be set to ""

specify the image format

---

os_migrate/plugins/module_utils/exc.py
os_migrate/plugins/module_utils/reference.py
os_migrate/plugins/module_utils/resource.py
os_migrate/plugins/module_utils/server.py
os_migrate/plugins/modules/import_workload_export_volumes.py
os_migrate/plugins/modules/import_workload_transfer_volumes.py
os_migrate/roles/export_workloads/defaults/main.yml
os_migrate/roles/export_workloads/tasks/main.yml
os_migrate/tests/unit/test_resource.py
os_migrate/tests/unit/test_server.py
tests/e2e/tenant/run_workload.yml
tests/e2e/test_as_tenant.yml

* This enables the boot_disk_copy migration parameter for
workloads. When it's `false`, server is booted from an image. When
it's `true`, server boot disk is copied and the destination
server is created as boot-from-volume.
* Default value for boot_disk_copy depends on each server. Servers
booted from a volume default to `true` (as that is the only sensible
option), servers booted from an image default to `false`.
* `image_ref` is added to the server serialization to track the Glance
image that should be used to create the server.
* E2e tests for workload migration are now testing these cases:
* Instance booted from an image, with boot_disk_copy: false.
* Instance booted from an image, with boot_disk_copy: true.

Migration of rebuildable servers

---

os_migrate/plugins/module_utils/server.py
os_migrate/tests/unit/test_server.py

This will ensure ssh-ability of servers which were migrated using the
from-image method. Naturally the ssh keypair needs to be migrated
before migrating the server.

Preserve keypair when creating a server from an image

---

Makefile

Currently, the container image build job is failing
as we are calling the toolbox build without the
variable TOOLBOX_BUILD. This patch defaults the value to 0
if not defined, which means, build the container image.

Fix: Assign a default value for reusing the toolbox image

---

Makefile

Im following now the same approach we have in another
variables check in the same makefile.
Even if locally the check works in the job we have
errors like: if [[ EUSE_TOOLBOX -eq "0" ]]; then \
Notice that EUSE instead or REUSE

Fix: Revert to conditional empty variable check

---

os_migrate/plugins/modules/import_workload_prelim.py
os_migrate/roles/import_workloads/tasks/main.yml
os_migrate/roles/import_workloads/tasks/workload.yml

Previously workload migration logs were stored directly in
os_migrate_data_dir together with resource YAMLs. This meant that when
migrating multiple workloads, the directory would get cluttered. Let's
separate workload migration logs into its own directory.

Store workload migration logs in a separate dir

---

docs/src/devel/contributing.rst
scripts/gitchangelog.rc

This patch adds a docs reference
for the commit's style convention.
Please enter the commit message for your changes. Lines starting

Dev: Docs minor improvement

---

Makefile

When running `make toolbox-build` to refresh the toolbox image, the
build is typically skipped if the image has been already built locally
before. Make sure we always rebuild by using `--no-cache`.

Dev: Do not use cache when building toolbox image

---

os_migrate/README.md

Taken from the official docs, the landing page should start talking
about what is OS Migrate rather than what is PCM.

Dev: Same wording on landing page as in official docs

---

docs/src/_exts/ansible-autodoc.py
docs/src/roles/role-import_security_group_rules.rst
toolbox/build/venv-requirements.txt

This patch renders the documentation including
the initial README.md file from each role.

Dev: Include role documentation in sphinx template

---

.github/workflows/consistency-functional.yml

It looks like devstack can't work with new pip version 20.3, which got
released a few hours ago:
Using python 3.6 to install /opt/stack/keystone
+ inc/python:pip_install:193               :   sudo -H LC_ALL=en_US.UTF-8 SETUPTOOLS_USE_DISTUTILS=stdlib http_proxy= https_proxy= no_proxy= PIP_FIND_LINKS= SETUPTOOLS_SYS_PATH_TECHNIQUE=rewrite python3.6 -m pip install -c /opt/stack/requirements/upper-constraints.txt -e /opt/stack/keystone
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement.. You can find …

Fix functional CI by pinning pip version

---

os_migrate/roles/conversion_host_content/tasks/centos.yml
os_migrate/roles/conversion_host_content/tasks/main.yml
os_migrate/roles/conversion_host_content/tasks/rhel.yml

I ran into a bug when trying to migrate workloads, the volume export
step crashed with:
qemu-img: Unable to initialize gcrypt
It turns out there was desync in package versions, we were installing
latest qemu-img but libgcrypt was old. We need to update to latest
when deploying the conversion hosts.
Resolves: https://github.com/os-migrate/os-migrate/issues/322

Update packages when deploying conversion hosts

---

os_migrate/roles/conversion_host_content/tasks/centos.yml
os_migrate/roles/conversion_host_content/tasks/main.yml
os_migrate/roles/conversion_host_content/tasks/rhel.yml

I ran into a bug when trying to migrate workloads, the volume export
step crashed with:
qemu-img: Unable to initialize gcrypt
It turns out there was desync in package versions, we were installing
latest qemu-img but libgcrypt was old. We need to update to latest
when deploying the conversion hosts.
Resolves: https://github.com/os-migrate/os-migrate/issues/322
(cherry picked from commit 3e68a4aad182472d8d343769c83640512551a673)

Backport for 0.6: Update packages when deploying conversion hosts

---

docs/src/modules/module-import_workload_source_check.rst
os_migrate/plugins/modules/import_workload_prelim.py
os_migrate/plugins/modules/import_workload_source_check.py
os_migrate/roles/import_workloads/tasks/workload.yml
os_migrate/tests/sanity/ignore-2.9.txt

During the workload import, the code was checking the workload status
via the export file.  If a server had been turned on or moved into
another state other than "SHUTOFF" since the export occured, the
workload import would fail.  This patch addresses that by checking
the source cloud via the openstacksdk to ensure the workload status
is "SHUTOFF" before attempting to migrate it.

Workload Source Check

---

tests/e2e/ansible.cfg
tests/func/ansible.cfg

This should let us inspect how much time is consumed by individual
tasks.

Dev: Add time profiling into CI logs

---

os_migrate/playbooks/deploy_conversion_hosts.yml

The updating and installing of packages on conversion hosts can take
minutes. These actions were done in series until now (src then dst),
but now they're done in parallel, which should speed up execution of
the conversion host deployment playbook.

New: Parallel installation of conversion hosts

---

.gitignore
scripts/docs-build.sh

The changelog contained entries like merge commits because the
changelog generator config path variable wasn't exported. This is now
fixed.

Dev: Fix changelog generation in 'make docs'

---

.github/workflows/docs-build-pr.yml
.github/workflows/docs-build.yml
Makefile

Instead of using the modules which are specific to Github
Actions, let's use 'make docs' to build documentation, be it locally by a
contributor, or in CI.

Dev: use 'make docs' to generate docs in Github Actions

---

os_migrate/plugins/module_utils/exc.py
os_migrate/plugins/module_utils/server.py
os_migrate/plugins/module_utils/server_floating_ip.py
os_migrate/tests/unit/test_server_floating_ip.py
tests/e2e/tenant/run_pre_workload.yml

New: Creation of Floating IPs on migrated workloads
A new migration parameter 'floating_ip_mode' is added into the
workload serialization. The current possible values are 'auto' and
'skip'.
* 'auto' means that floating IP creation is attempted for the VM, if
the source VM had floating IP(s). The floating IP info is already
being exported with the workload.
Currently we only support auto-assignment of the floating IP
address. (Exact assignment is typically not allowed by policy for
tenants, but this should be investigated too.)
Each floating IP serialization has a 'floating_network_ref'
reference, which specifies the network where the floating IP should
be created. The 'fixed_ip_address' parameter controls which
port/address will the floating IP attach to.
* 'skip' means that even if the …

New: Creation of Floating IPs on migrated workloads

---

os_migrate/playbooks/delete_conversion_hosts.yml
os_migrate/roles/conversion_host/tasks/conv_host_inventory.yml
os_migrate/roles/conversion_host/tasks/unregister.yml
tests/e2e/test_as_tenant.yml

This patch adds logic to unsubscribe systems from RHSM when using
RHEL as the OS for a conversion host.  The unsubscribe is called
for both the source and destination conversion hosts just before
they are deleted.

New: Adds Logic to Unsubscribe RHEL Conversion Hosts

---

scripts/_skeleton_role_/meta/main.yml.j2

This patch fixes the skeleton template
for creating new roles.

Dev: Fix meta template

---

.github/workflows/consistency-functional.yml

This reverts commit c0ae23709ef96d6426fc9219e2dc56dd71c5f56a. It was a
temporary measure to fix CI broken by Devstack, which was in turn
broken by a new pip release.
Context:
https://github.com/os-migrate/os-migrate/issues/317
https://github.com/os-migrate/os-migrate/pull/318

Dev: Revert "Fix functional CI by pinning pip version"

---

os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/resource.py
os_migrate/plugins/module_utils/router.py
os_migrate/tests/unit/test_resource.py
tests/e2e/tenant/run_pre_workload.yml

Dev: Mechanism for skipping falsey params
Empty lists usually don't make sense to feed into the API requests as
parameters. Often the results of feeding an empty list vs. not
specifying the parameter can be the same, but it can matter in some
cases, e.g. if Neutron router availability zone extension is disabled,
the parameter must not be specified in the request.
--------
Chg: Don't feed availability_zone_hints into requests when empty
The availability_zone_hints parameter for routers and networks can
often be an empty list. Previously we've fed it as-is into the API
requests. However, if the extension for network/router availability
zones isn't enabled, this can cause the request to fail.
We now only use the availability_zone_hints parameter when its not
empty. This should have no effect …

Chg: Don't feed availability_zone_hints into requests when empty 

---

os_migrate/roles/conversion_host_content/defaults/main.yml
os_migrate/roles/conversion_host_content/tasks/rhel.yml

Chg: Shorter names for RHSM variables
The RHSM variables are renamed from previous pattern of
e.g. 'os_migrate_conversion_host_content_rhsm_user' to
e.g. 'os_migrate_conversion_rhsm_user' which is shorter but should
still be descriptive enough and not risk a naming collision.
The 'user' variable is also renamed to 'username' to match the
parameter naming on the redhat_subscription module.
------------
Chg: Pass through all RHSM parameters for conversion hosts
All parameters supported by the redhat_subscription Ansible module are
now exposed as variables for the conversion host content installation.

Chg: Pass through all RHSM parameters for conversion hosts

---

toolbox/build/venv-requirements.txt

The pin works around this breakage in Ansible:
'BadRequestException: 400: Client Error for url:
http://10.0.110.233:9696/v2.0/security-group-rules, Unrecognized
attribute(s) ''remote_address_group_id'''
Resolves: https://github.com/os-migrate/os-migrate/issues/350

Pin openstacksdk version due to os_security_group_rule module breakage

---

os_migrate/plugins/module_utils/server.py

When migrating a server which is boot-from-image in source cloud, and
boot-from-volume in destination cloud (due to setting `boot_disk_copy:
true`), the server creation would still try to look up `image_ref` in
the destination cloud, and fail if the image doesn't exist.
This is now fixed. With `boot_disk_copy: true` we don't need any
images in destination, so we no longer perform an image lookup.
Resolves: https://github.com/os-migrate/os-migrate/issues/347

Fix: Do not look up server image when boot_disk_copy: true

---

os_migrate/plugins/module_utils/reference.py
tests/e2e/tenant/seed_workload.yml
tests/e2e/test_as_tenant.yml

The `connection.image.find_image` method doesn't support filter
arguments (like project_id), unlike other find methods. This caused
failures when looking up images to be used for servers, when the image
was owned by tenant (non-public).
A custom image lookup method is now implemented in our reference.py
module, utilizing `images()` rather than `find_image()`.
End-to-end tests are also amended to test one workload spawned from
public image, and one from tenant-owned image.
Resolves: https://github.com/os-migrate/os-migrate/issues/346

Fix: Fix image lookup for images owned by tenant

---

os_migrate/playbooks/deploy_conversion_hosts.yml

Previously when the source or destination conversion host encountered
some errror, Ansible would mark that host as failed and not run any
other tasks there, but it would continue to run tasks on other hosts,
most notably the migrator. This meant that e.g. subscription errors
wouldn't stop the playbook immediately, and if conversion host
deployment was included into a more complex migration playbook, the
migration itself would fail much later with a non-obvious error. This
is now fixed: whenever an error during conversion host deployment
happens, the playbook stops right away.

Fix: Always stop on errors in conversion host deployment

---

os_migrate/plugins/module_utils/workload_common.py

The current timeout for OpenStack operations during workload migration
is 10 minutes. This can be too short when working with large storage
volumes. We should make the timeout configurable, but as first
alleviation we increase the timeout to 30 minutes. This should still
be enough to fail in reasonable time when things get stuck, but it
shouldn't produce as many false alarms.

Fix: Loosen OpenStack operation timeouts in workload migration

---

os_migrate/plugins/module_utils/common.py
os_migrate/plugins/module_utils/network.py
os_migrate/plugins/module_utils/resource.py
os_migrate/plugins/module_utils/router.py
os_migrate/plugins/module_utils/subnet.py
os_migrate/tests/unit/test_network.py
os_migrate/tests/unit/test_resource.py
os_migrate/tests/unit/test_router.py
os_migrate/tests/unit/test_subnet.py
tests/func/tenant/seed/network.yml
tests/func/tenant/seed/router.yml
tests/func/tenant/seed/subnet.yml

Dev: Add after-update (and after-create) hook mechanism to resources
Since it is reasonable to expect that similar or the same actions will
take place in after create and after update, we have a single
`_hook_after_update` method which gets called in both events. It has
an `is_create` parameter in case distinguishing between the two events
is necessary.
------
Chg: Preserve tags during migration of routers, networks, subnets
The tags on networking resources cannot be set during the initial
creation request. Previously we weren't setting tags at all during
migration of networking resources. We are now migrating tags correctly
on routers, networks and subnets using a post-create/update hook.

Chg: Preserve tags during migration of routers, networks, subnets

---

os_migrate/plugins/module_utils/image.py
os_migrate/plugins/module_utils/reference.py
scripts/build.sh
toolbox/build/venv-requirements-lower-bound.txt

We started testing with two OpenStack SDK versions:
* 0.52.x which is close to latest but not yet affected by a security
group rules bug [1].
* 0.36.x which is in Train release (OSP 16).
[1] https://storyboard.openstack.org/#!/story/2008577

New: Testing with lower bound requirements

---

os_migrate/plugins/modules/import_workload_prelim.py

Previously we just fed the desired server_name into the
`compute.servers()` query when checking whether a server has already
been migrated. However, Nova API performs a regular expression search,
so this condition matched on any substring occurence. This is now
fixed by wrapping the search term between ^ and $.
Note: We use Glance API in a similar way due to it also not having a
find method with project filters. Glance API seems to do exact
matching on the name query.
Resolves: https://github.com/os-migrate/os-migrate/issues/365

Fix: Exact name match on idempotency check during workload migration

---

os_migrate/plugins/modules/import_workload_transfer_volumes.py
os_migrate/roles/conversion_host_content/tasks/centos.yml
os_migrate/roles/conversion_host_content/tasks/rhel.yml

To have the volume sparsification work, two things have changed:
* We install and start libvirt in the conversion hosts.
* We specify that the NBD backends of volume qcow2 images are of raw
format.
Resolves: https://github.com/os-migrate/os-migrate/issues/364

Fix: Sparsification of volumes

---

.github/workflows/container-image-build.yml
.github/workflows/docs-build-pr.yml
.github/workflows/docs-build.yml

This PR removes the podman install in the pending
CI jobs as it is now shipped directly in the Ubuntu
guest image.

Dev: Remove podman install from CI jobs

---

.github/workflows/consistency-functional.yml

This commit enables to deploy
devstack master when testing os-migrate

Dev: Enable devstack master

---

toolbox/build/venv-wrapper

In toolbox dir, we have the run/shell script pairs, one for running a
command in a container, another for launching a shell in a
container. However, it can be done so that if no arguments are passed
to the 'run' script, it acts the same way as the 'shell' script. This
is already true for the plain 'run' and the 'vagrant-run', only
'venv-run' is edited to achieve the behavior described above.

Dev: Run shell when venv-run is passed no arguments

---

.github/workflows/container-image-build.yml

Podman is already installed in the
Ubuntu latest image used in the CI.
If we trigger a package update the
CI breaks because the newer version
can not be found in kubic.

Dev: Do not install podman

---

Makefile
docs/src/user/variables-guide.rst
docs/src/user/walkthrough.rst
os_migrate/plugins/filter/stringfilter.py
os_migrate/roles/export_images/defaults/main.yml
os_migrate/roles/import_flavors/defaults/main.yml
os_migrate/roles/import_flavors/tasks/main.yml
os_migrate/roles/import_images/defaults/main.yml
os_migrate/roles/import_images/tasks/main.yml
os_migrate/roles/import_keypairs/defaults/main.yml
os_migrate/roles/import_keypairs/tasks/main.yml
os_migrate/roles/import_networks/defaults/main.yml
os_migrate/roles/import_networks/tasks/main.yml
os_migrate/roles/import_projects/defaults/main.yml
os_migrate/roles/import_projects/tasks/main.yml
os_migrate/roles/import_router_interfaces/defaults/main.yml
os_migrate/roles/import_router_interfaces/tasks/main.yml
os_migrate/roles/import_routers/defaults/main.yml
os_migrate/roles/import_routers/tasks/main.yml
os_migrate/roles/import_security_group_rules/defaults/main.yml
os_migrate/roles/import_security_group_rules/tasks/main.yml
os_migrate/roles/import_security_groups/defaults/main.yml
os_migrate/roles/import_security_groups/tasks/main.yml
os_migrate/roles/import_subnets/defaults/main.yml
os_migrate/roles/import_subnets/tasks/main.yml
os_migrate/roles/import_users/defaults/main.yml
os_migrate/roles/import_users/tasks/main.yml
os_migrate/roles/import_workloads/defaults/main.yml
os_migrate/roles/import_workloads/tasks/main.yml
os_migrate/tests/unit/test_stringfilter.py

The `os_migrate_<resources>_filter` variables that are already used to
filter resources during export, are now respected during import
too. That means user can choose whether they want to filter during
export or during import, or even combine the approaches to export a
subset of the existing resources, and further limit them into smaller
chunks during import.
Resolves: #367

New: Filters in import playbooks

---

docs/src/modules/module-import_workload_dst_check.rst
os_migrate/plugins/module_utils/resource.py
os_migrate/plugins/modules/import_workload_dst_check.py
os_migrate/roles/import_workloads/tasks/workload.yml
os_migrate/tests/sanity/ignore-2.9.txt
os_migrate/tests/unit/test_resource.py

Before workload storage migration is started, it is now validated that
the server's references to resources like flavor, image, security
group, network, or subnet can be properly resolved in the destination
cloud. This aims to avoid situations where the block storage is first
successfully copied and then the server creation fails due to a
trivial problem.

New: Destination cloud prerequisites validation for workload migration

---

toolbox/build/build.sh

The new version of Python's cryptography package has a native
extension written in Rust, so we need Rust toolchain to be able to
install Ansible from pip.
Also splitting the dependencies to one per line, going forward this
will make it easier to track why some dependency was added.

Dev: Fix toolbox build by installing Rust

---

os_migrate/plugins/module_utils/security_group.py
tests/func/tenant/run/security_group.yml

When creating a security group, OpenStack automatically inserts 2
basic rules to allow all egress traffic (one for IPv4, one for
IPv6). Creating these blanket-allow rules automatically in destination
is undesirable, as the user may have replaced the default rules with
some more restrictive ones in the source security group.
When creating a new destination security group, we now immediately
delete the auto-created rules. If the source security group kept the
default rules, they got exported like any other rules, and will be
imported into destination during rule import.

Fix: Ensure new security groups don't have auto-created rules

---

os_migrate/plugins/module_utils/server.py
os_migrate/plugins/modules/import_workload_create_instance.py

The import_workload_create_instance module now outputs a full workload
serialization of the server created in the destination cloud. When
running Ansible in verbose mode, it can be used as debugging
information, and allows for direct comparison of the destination
workload to the contents of workloads.yml file.
This requires that the import_workload_create_instance module waits
for the Nova server to enter ACTIVE state, to have full information
available. Typically this only adds several seconds to the workload
migration time, which is negligible in the full picture. By waiting,
we can also make sure the server indeed does go ACTIVE and not into
ERROR state, which may have previously gone unnoticed with the "fire
and forget" server creation approach.

New: Ensure Nova server creation is successful and emit detailed info

---

os_migrate/plugins/module_utils/flavor.py
tests/func/admin/clean/flavor.yml
tests/func/admin/idempotence/flavor.yml
tests/func/admin/run/flavor.yml
tests/func/admin/seed/flavor.yml

Flavors were prevented from importing due to several issues around
parameters passed into the flavor creation API request, this is now
fixed. Extra specs are now being set after the flavor is created.

Fix: Flavor export/import

---

os_migrate/plugins/module_utils/workload_common.py
os_migrate/plugins/modules/import_workload_dst_failure_cleanup.py
os_migrate/plugins/modules/import_workload_export_volumes.py
os_migrate/plugins/modules/import_workload_src_cleanup.py
os_migrate/plugins/modules/import_workload_transfer_volumes.py
os_migrate/roles/import_workloads/defaults/main.yml
os_migrate/roles/import_workloads/tasks/workload.yml

Until now, non-immediate actions and blocking calls to OpenStack SDK
within workload migration have used a hard-coded timeout of 30
minutes. New variable `os_migrate_timeout` has been introduced for
setting the timeout (in seconds), the value is 1800 (= 30 minutes).

New: Configurable timeout for non-immediate actions

---

os_migrate/plugins/module_utils/project.py
os_migrate/plugins/module_utils/reference.py
tests/func/admin/clean/all.yml
tests/func/admin/clean/domain.yml
tests/func/admin/idempotence/project.yml
tests/func/admin/idempotence/user.yml
tests/func/admin/run/all.yml
tests/func/admin/run/project.yml
tests/func/admin/run/user.yml
tests/func/admin/seed/all.yml
tests/func/admin/seed/domain.yml
tests/func/admin/seed/project.yml
tests/func/admin/seed/user.yml

Keystone has 2 types of domains - domain objects, and project objects
with is_domain=True. OS Migrate correctly worked only with the latter
until now. Domain objects are now working too, and it is tested in
functional tests.
Resolves #403

Fix: Project parent references allow domains too

---

os_migrate/roles/conversion_host/defaults/main.yml
tests/e2e/tenant/seed_pre_workload.yml

This commit cast the os_migrate_src_release and
os_migrate_dst_release variables to integers.
Fixes: #408

fix: make sure the src/dst release is an integer

---

os_migrate/plugins/module_utils/workload_common.py
os_migrate/plugins/modules/import_workload_dst_failure_cleanup.py
os_migrate/plugins/modules/import_workload_export_volumes.py
os_migrate/plugins/modules/import_workload_src_cleanup.py
os_migrate/plugins/modules/import_workload_transfer_volumes.py
os_migrate/tests/unit/test_flavor.py
os_migrate/tests/unit/test_keypair.py
os_migrate/tests/unit/test_project.py
os_migrate/tests/unit/test_server.py
os_migrate/tests/unit/test_user.py
toolbox/build/build.sh

All tests running via the `ansible-test` tool were not run for some
time. This was due to Ansible looking for specific Python versions to
run the tests with. The latest version it was looking for was Python
3.8, but in the toolbox container we had Python 3.9. This caused
ansible-test to silently skip running all tests and still return 0, so
this went completely unnoticed in CI.
The toolbox container now explicitly install Python 3.8 and uses it to
create the virtualenv. This caused all the tests to start running
again, and they failed, so minimal fixes to make them pass again are
included in the commit too.

Dev: Fix running tests via Ansible test tools

---

os_migrate/plugins/module_utils/router_interface.py
os_migrate/tests/unit/test_router_interface.py

Previously when exporting router interfaces, only ports with
device_owner value of 'network:router_interface' were picked up. This
would not export interfaces correctly for HA/DVR routers. We now also
export ports with device_owner values of
'network:ha_router_replicated_interface' and
'network:router_interface_distributed' for HA/DVR routers.

Fix: Export RouterInterface of HA and DVR routers

---

os_migrate/roles/conversion_host/tasks/main.yml

This commit adds the hability to remove automatically
the volume created with the conversion host once
the VM is destroyed.

New: delete volumes when deleting the conversion hosts

---

os_migrate/roles/conversion_host/defaults/main.yml
os_migrate/roles/conversion_host/tasks/main.yml

This commit allows to increase the hardwired default timeout of
600 seconds when deploying the conversion hosts.
In this case, when the overlay network provider takes longer to
assign a floating IP, there might be needed to increase this
default.

fix: increase timeouts when deployment takes more than default

---

.github/workflows/consistency-functional.yml

DEvstack now uses OVN, this commit disables those
agents not needed.

dev: fix CI, disable neutron agents not used with OVN

---

os_migrate/roles/conversion_host/tasks/conv_host_inventory.yml
os_migrate/roles/conversion_host/tasks/conv_hosts_inventory.yml

This commit allows having two additional
groups for the conversion hosts.
conversion_hosts_src and conversion_hosts_dst

Dev: add the conversion hosts to specific groups

---

.github/workflows/consistency-functional.yml

OVN_L3_CREATE_PUBLIC_NETWORK is set to true now
by default. This commit disables the L3 public
network.

Dev: Fix OVN options

---

os_migrate/plugins/module_utils/flavor.py
tests/func/admin/clean/flavor.yml
tests/func/admin/seed/flavor.yml

Most recent APIs+SDKs always give empty hash for extra_specs. However,
some older versions may also return extra_specs as None. This could
break OS Migrate. The issue is now fixed by making sure we set
internal variables to {} whenever some extra_specs parameter (either
loaded from YAML or queried from SDK) is None.

Fix: Handle when flavor extra_specs are reported as None from API

---

.github/workflows/consistency-functional.yml

This commit skips the execution of the file-changes-action
GitHub action when running the scheduled job. This is because
the file-changes-action action waits for a PR id to determine
which files changed, and when running the scheduled job this
variable will be NaN.

Dev: skip file-changes-action on the scheduled job

---

.github/workflows/consistency-functional.yml

This commit adds the schedule check also in the
functional tests section. We added it on the project
build job and it succeded, now we should do the same when running
the functional tests.

Dev: skip trilom file check in the functional tests

---

os_migrate/README.md

This commit updates the README to have the functional test badge to point
to the periodic result instead of the test result from push events.

Dev: Update README to point functional tests badge to the periodic job

---

os_migrate/plugins/module_utils/flavor.py

The previous implementation of extra_specs import on flavors only
worked with SDK >=0.51. A fallback implementation is now added for
running with older SDKs. This fallback implementation can be dropped
in the future after we drop support for SDK <0.51.

Fix: Flavor extra_specs import with OpenStack SDK older than 0.51

---

os_migrate/plugins/module_utils/keypair.py

SDK should support 'type' on keypairs since 0.32 [1], however even
with 0.36 this error still appears when testing against latest
Devstack:
openstack.exceptions.BadRequestException: BadRequestException: 400:
Client Error for url: http://192.168.122.93/compute/v2.1/os-keypairs,
Invalid input for field/attribute keypair. Value: {'type': 'ssh',
<REDACTED>, 'name': 'osm_keypair'}. Additional properties are not
allowed ('type' was unexpected).
This error disappears when testing with latest SDK. It's not easy to
track down what exact combinations of SDK/API are needed to allow for
'type' in keypair creation request. So we'll first try with 'type',
and if that request fails with error 400 (Bad Request), then we retry
without 'type'. If that request still fails, the keypair import module
fails …

Fix: Only use 'type' on keypairs when it is supported

---

os_migrate/roles/import_workloads/tasks/main.yml

In conversion host reachability check, with the `wait_for` Ansible
module we used `delay` of 10 seconds, which caused a delay before the
first check, causing unnecessary slowdown (20 seconds in total) of the
import_workloads playbook. What we probably meant to use was `sleep`,
which sets the interval between checks. This is now fixed and the
`sleep` property is set to 5 seconds.

Fix: Remove unnecessary delay in conversion host reachability check

---

.github/workflows/consistency-functional.yml
os_migrate/galaxy.yml
os_migrate/plugins/module_utils/const.py
os_migrate/plugins/module_utils/flavor.py
os_migrate/plugins/module_utils/keypair.py
os_migrate/roles/import_workloads/tasks/main.yml
scripts/linters.sh
tests/func/admin/clean/flavor.yml
tests/func/admin/seed/flavor.yml
tests/func/tenant/data/validate_data_dir/invalid/networks-duplicate.yml
tests/func/tenant/data/validate_data_dir/invalid/networks.yml
tests/func/tenant/data/validate_data_dir/valid/networks.yml

Fix: Handle when flavor extra_specs are reported as None from API
Fix: Flavor extra_specs import with OpenStack SDK older than 0.51
Fix: Only use 'type' on keypairs when it is supported
Fix: Remove unnecessary delay in conversion host reachability check
+ 'Dev' patches which look like they may be required to keep tests passing

Prepare release 0.8.3 with recent fixes

---

docs/src/devel/dev-env-setup.rst

Add links to Podman and Buildah for easier discovery and also include
the prerequisite that a git clone of the os-migrate repo is also required

Dev: Expand prerequisites for developer environment setup

---

os_migrate/roles/conversion_host/defaults/main.yml

Previously we had conversion host network MTUs decided by variables
`os_migrate_src_release` and `os_migrate_dst_release` and decided MTUs
for conversion host network based on those. These were test-specific
decisions leaking into production settings. We now default the MTU
parameters to Ansible's `omit` special value, which means the module
responsible for creating the network will not specify any value in the
network creation API request, and the MTU will be autoselected by the
cloud.
If the defaults result in undesirable values, the MTUs can still be
explicitly overriden via `os_migrate_src_conversion_net_mtu` and
`os_migrate_dst_conversion_net_mtu` variables.
This fix also removes dependency of production code on
`os_migrate_src_release` and `os_migrate_dst_release` variables, as …

Fix: Conversion host network MTUs default to cloud defaults

---

os_migrate/meta/runtime.yml
scripts/linters.sh
toolbox/Dockerfile

Publishing 0.9.0 failed with:
ERROR! Galaxy import process failed: 'requires_ansible' in
meta/runtime.yml is mandatory, but no meta/runtime.yml found (Code:
None)
It seems there is a new requirement for Ansible collections of adding
meta/runtime.yml [1], and the minimal runtime.yml seems to consist of
supported range of Ansible versions. Let's start defensively with 2.9
only, as that's what we currently CI, and expand/move the list
according to what we test.
[1] https://github.com/ansible/ansible/commit/a9eb8b04882669bd17cd82780c908863e7504886

Dev: Add minimal runtime.yml for the Ansible collection

---

tests/e2e/tenant/scenario_variables.yml

This commit moves forward the usage of
CentOS 8 stream in the end-to-end testing
of OS migrate.

Dev: Use CentOS 8 stream instead of CentOS 8

---

os_migrate/playbooks/deploy_conversion_hosts.yml
os_migrate/roles/conversion_host/defaults/main.yml
os_migrate/roles/conversion_host/tasks/enable_password_access.yml

This commit allows to configure a default password in both
centos and cloud-user users, this can help connecting directly
to the hosts with a default password disabled by default.
Added os_migrate_conversion_host_ssh_user_enable_password_access
disabled by default.

New: Allow ssh access to conversion host using a default password

---

os_migrate/plugins/module_utils/resource.py
os_migrate/tests/unit/test_resource.py

For resources which have a name property validate that it is non empty.
This fixes an issue where resources with empty names are not included in the check
for uniqueness/idempotence. By checking for empty names we avoid this issue.

Fix: For resources that have name, reject migration with empty name

---

docs/src/user/variables-guide.rst
os_migrate/playbooks/deploy_conversion_hosts.yml
os_migrate/roles/conversion_host_content/defaults/main.yml
os_migrate/roles/conversion_host_content/tasks/main.yml

This commit allows to run custom bash scripts in
the conversion hosts before and after the content
playbook.

new: allow running scripts in the conversion hosts

---

os_migrate/plugins/module_utils/filesystem.py
os_migrate/plugins/module_utils/workload_common.py
os_migrate/plugins/modules/import_workload_transfer_volumes.py
os_migrate/tests/unit/test_filesystem.py

Lint checks are failing because of
unspecified-encoding: Using open
without explicitly specifying an encoding

dev: fix encondings

---

toolbox/Dockerfile
toolbox/vagrant/vagrant-config.yml
toolbox/vagrant/vagrant-up

The expected Fedora version for Devstack is now 34:
https://opendev.org/openstack/devstack/src/commit/e102559f87b3b2afb5ad0aa874f9bfa98c269624/stack.sh

Dev: Update toolbox and Vagrant base to Fedora 34

---

docs/src/user/walkthrough.rst

This commit fixes some wrong links
in the docs

docs: fix walkthrough links

---

docs/src/user/variables-guide.rst
os_migrate/playbooks/delete_conversion_hosts.yml
os_migrate/roles/conversion_host/defaults/main.yml
os_migrate/roles/conversion_host/tasks/delete.yml

This commit enables users to detach or demove floating IPs
when deleting the conversion hosts.

new: allow deleting or detaching the conversion hosts FIPs

---

docs/src/user/how-it-works-workload-migration.rst

I used `image` instead of `figure` in RST doc and the image was not
showing. This is now fixed.

Dev: Fix for image in the docs not showing

---

os_migrate/plugins/module_utils/server.py
os_migrate/tests/unit/test_server.py

When validating workload migration we should only validate if the keypair
specified in the workload/vm is present in the destination environment if the
workload/vm has a keypair associated with it.

Fix: Only perform keypair lookup in dst if server has keypair

---

.gitignore

For developers using any of the intellij suite of IDEs adding
'.idea' to git ignore makes development a little cleaner.

Dev: Add intellij '.idea' directory to ignore list

---

Makefile
docs/src/user/migration-params-guide.rst
os_migrate/plugins/module_utils/server.py
os_migrate/plugins/module_utils/server_floating_ip.py
os_migrate/tests/unit/test_server_floating_ip.py
tests/e2e/tenant/clean_workload.yml
tests/e2e/tenant/clean_workload_existing_fip.yml
tests/e2e/tenant/run_workload.yml
tests/e2e/tenant/run_workload_existing_fip.yml
tests/e2e/test_as_tenant.yml

Two new floating_ip_mode migration parameter values are introduced:
'new' and 'existing'. The modes now behave this way:
* 'skip' - Do not create any floating IPs.
* 'new' - Create a new floating IP (auto-assigned address).
* 'existing' - Assume the floating IP address specified in the
workload serialization is already assigned to the destination
project, but not attached. Attach this floating IP. If this is not
possible for some reason, fail.
* 'auto' - Attempt the 'existing' method of floating IP assignment,
but instead of failing, fall back to the 'new' method.

New: Allow using pre-existing floating IPs for migrated servers

---

docs/src/user/variables-guide.rst
os_migrate/playbooks/deploy_conversion_hosts.yml
os_migrate/roles/conversion_host/defaults/main.yml
os_migrate/roles/conversion_host/tasks/main.yml

The operator can now control if conversion hosts are backed by a local
Nova disk (still the default), or if they are created as
boot-from-volume. The parameters which control the behavior are:
os_migrate_src_conversion_host_boot_from_volume
os_migrate_dst_conversion_host_boot_from_volume

New: Allow creating conversion hosts as boot-from-volume servers

---

.github/workflows/consistency-functional.yml
Makefile

Devstack recently changed [1] the default authorizations on the demo
users, so we adapt the usage of accounts to get the original behavior.
This means using member+reader accounts for the tests.
[1] https://github.com/openstack/devstack/commit/9c81321bfc694bd511dee8dd5d04273e368e5545

Dev: Fix functional tests after a Devstack auth change

---

os_migrate/plugins/module_utils/resource.py
os_migrate/roles/conversion_host_content/tasks/main.yml
os_migrate/roles/prelude_common/tasks/main.yml
scripts/check_fqcn.py
tests/e2e/tasks/tenant/clean_workload_existing_fip.yml
tests/e2e/tasks/tenant/run_workload_existing_fip.yml
tests/func/tasks/admin/clean/user_keypair.yml
tests/func/tasks/admin/seed/user_keypair.yml
tests/func/tasks/tenant/independent/validate_data_dir.yml
toolbox/vagrant/ansible/roles/devstack/tasks/start.yml

Currently the migrator host is not limited to be only
CentOS, Fedora, or RHEL. In the case a user runs OS
migrate from a Linux distribution which is not using
Bash as the default terminal, options like pipefail
might not be availabe (i.e. Ubuntu and ZSH) for
those cases we need to make explicit that the shell
we will use is Bash.
This commit enforce to use and set explicitly
the executable when running ansible.builtin.shell.

Fix: enforce the executable argument when executing shell

---

os_migrate/plugins/module_utils/exc.py
os_migrate/plugins/module_utils/filesystem.py

After upgrading without clearing old exported data, OS Migrate refuses
to parse the old data files. The resulting error message was not clear
enough about the likely root cause and solution. Path to the
problematic file and extra hints are now added to the exception
message, as this is a relatively common pitfall.

Chg: Improve error message on data version mismatch

---

docs/src/user/install-from-galaxy.rst

The link on the user/install-from-galaxy.html address to user/install-from-source.md, which does not exit,  instead of user/install-from-source.html

Docs: fix link on install-from-galaxy which address to install-from-source

---

docs/src/devel/dev-env-setup.rst

The `--id auto` parameter has to be removed from the flavor creation
because it tries to literally set flavor IDs to "auto", and as we're
creating 2 of those, they conflict. We should simply remove the `--id`
parameter to get the ID autogenerated.
The flavor RAM for the conversion host is increased so that it doesn't
get OOM killed.
We also add instructions on how to create public network, with
parameters for environments deployed with Infrared Virsh provisioning
plugin.
Minor formatting fixes are included.

Dev: Fix and extend e2e dev env setup instructions

---

os_migrate/roles/prelude_common/tasks/main.yml

Using shell for getting pip version leads to several highly possible
side effects. As example, you verify opensatcksdk persistance against
ENV however following tasks will use ansible_python_interpreter that
likely differ if virtualenv is used for ansible.
Another side effect is that openstacksdk could be installed in venv
which is not respected by shell when you provide interpreter for host
explicitly.
With this patch we replace shell with pip_package_info module that
collects all installed packages against ansible_python_interpeter.

Fix: Replace akward openstacksdk version check

---

.github/workflows/consistency-functional.yml

This commit removes the libmysqlclient-dev
package as is not available anymore.

dev: remove libmysqlclient-dev

---

os_migrate/plugins/module_utils/subnet.py
os_migrate/tests/unit/test_subnet.py

Subnets with multiple allocation pools previously crashed on export
due to an issue with parameter sorting. This is now fixed.

fix: Export of subnets with multiple allocation pools

---

toolbox/build/venv-requirements.txt

We are getting random breakages whenever something changes in the best
practices of some lint dependencies. Let's pin the test+lint
dependencies so that we tackle the updating of these willingly, rather
than randomly being hit with CI breakage.

dev: Pin test/lint dependencies to reduce random CI issues

---

.github/workflows/consistency-functional.yml
Makefile

Issue is related to pip - pushed a fix #556 to handle pip failure, another breakage in the files change action due to that code handling 2 different events from GitHub Actions push & pull_request. When creating a new branch for a PR, push will be triggered immediately before the PR gets created The GitHub API / GitHub context base commit is then 0000000000000000000000000000000000000000, The get-changed-files action needs to have a non 0/empty base commit to be able to diff, Defining both push (and specify the branches) and pull_request solves the problem, I recall running into this problem before with pip and we ended up adding the -no-cache flag somewhere, from docs looks like upgrading pip before we do anything fixes that other breakage. 
Error of file change action:
```
Run …
```

dev: patch to ci pip platformdirs and github action

---

scripts/build.sh

This commit fixes the
`ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: 'cachecontrol'`
error in the functional tests execution.

dev: make sure pip is installed

---

docs/src/user/install-from-galaxy.rst

Release 0.99.0 of openstacksdk brings major breaking interface changes.

Cap openstacksdk below 0.99

---

toolbox/vagrant/ansible/roles/devstack/tasks/config.yml
toolbox/vagrant/ansible/roles/devstack/tasks/prereqs.yml

Drop Fedora support
Fedora 36 is EOL, also opendev is dropping support for Fedora images
completely since interest in running jobs on that platform is no longer
existing. CentOS 9 Stream has evolved as replacement platform for new
features.
Only drop the Zuul configuration and the tag in stack.sh for now plus
update some docs. Cleanup of the deployment code will be done in a
second step.
Change-Id: Ica483fde27346e3939b5fc0d7e0a6dfeae0e8d1e
changes/67/885467/1
https://opendev.org/openstack/devstack/commit/fbc1865dc4e5b84ebafaf1d30cffc582ae3f0c0f

dev: check for unsupported distro

---

.github/workflows/consistency-functional.yml
docs/src/devel/dev-env-setup.rst
os_migrate/README.md
os_migrate/roles/conversion_host/defaults/main.yml
os_migrate/roles/conversion_host/meta/main.yml
os_migrate/roles/conversion_host_content/defaults/main.yml
scripts/build.sh

As noted in #637 there seem to be some warning outputs from ansible-lint. This is in relation to galaxy info platforms module and its version for fedora distros. Here is a similar issue found with another distro, https://github.com/ansible/ansible-lint/issues/3067. As of `6.13.0` there is support up to fedora 37, https://github.com/ansible/ansible-lint/blob/v6.13.0/src/ansiblelint/schemas/meta.json. The goal of this PR is to silence the warnings if possible, and update the functional CI given bugs with pip cachecontrol and ovs seen in other work streams.

oth: Patch to functional ci

---

os_migrate/roles/conversion_host/tasks/create_fip.yml
tests/e2e/tasks/tenant/run_workload_existing_fip.yml

We observed the floating IP creation for conversion hosts fail when trying to use the code path that uses predefined IP address rather than an auto-generated one. This module call is missing a 'network' parameter:
https://github.com/os-migrate/os-migrate/blob/426121f307bf0078c1c72b6dd48980849db2c768/os_migrate/roles/conversion_host/tasks/create_fip.yml#L2

fix: patch for network param missing from fip creation

---

toolbox/vagrant/vagrant-up

Since the older Fedora releases have been migrated to `archives.fedoraproject.org`, the `vagrant-up` command failed because the image wasn't found.

fix: Update Fedora 36 Vagrant image URL

---

.ansible-lint
os_migrate/plugins/module_utils/workload_common.py
scripts/linters.sh
tests/e2e/tasks/tenant/scenario_variables.yml
toolbox/Dockerfile
toolbox/build/build.sh
toolbox/build/venv-requirements.txt
toolbox/vagrant/Vagrantfile
toolbox/vagrant/ansible/roles/devstack/tasks/config.yml
toolbox/vagrant/ansible/roles/devstack/tasks/main.yml
toolbox/vagrant/ansible/roles/devstack/tasks/prereqs.yml
toolbox/vagrant/ansible/roles/devstack/tasks/run.yml
toolbox/vagrant/ansible/roles/devstack/tasks/start.yml
toolbox/vagrant/ansible/roles/devstack/templates/local.conf.j2
toolbox/vagrant/vagrant-config.yml
toolbox/vagrant/vagrant-sync/preconfigure.sh
toolbox/vagrant/vagrant-up

- The base image for the toolbox container has been updated to Fedora 40.
- The base image for Vagrant has been switched from Fedora 36 to CentOS Stream 9.
- Python packages have been updated and pinned to their latest stable versions.
- Official vagrant build will be used and vagrant-livirt plugin will be installed from upstream.
- Devstack is now configured on `2023.1` branch.

dev: Upgrade of the toolbox container and dependencies bump

---

.github/workflows/consistency-functional.yml
.github/workflows/container-image-build.yml
.github/workflows/docs-build-pr.yml
.github/workflows/docs-build.yml
toolbox/build/build.sh

Several checks were failing due to deprecated github actions and incompatibility between component versions.
* `action/checkout` has been updated to `v4`
* `action/upload` artifact has been updated to `v4`
* `action/setup-python` invocations have been removed since they weren't used
* `devstack` has been configured to fetch `stable/2023.1` branch rather than `master`
* Runner image has been changed from `ubuntu-latest` to `ubuntu-20.04` to be compatible with `Antelope` release of `devstack`
* `mysql` and `rabbitmq` images version have been pinned
* removed `sudo` from `build.sh` commands since commands are executed as root and sudo isn't available and/or configured on github runners.
* removed `pip` commands which aren't needed anymore
* removed old workarounds for devstack

dev: refactoring of github checks

---

toolbox/build/venv-requirements.txt

passlib is required by `password_hash` ansible filter and its absence led to a failure while executing a change password task

dev: add passlib as requirement

---

os_migrate/playbooks/export_workloads.yml
os_migrate/roles/conversion_host_content/tasks/centos.yml
tests/e2e/tasks/tenant/run_workload.yml
tests/e2e/tasks/tenant/seed_pre_workload.yml
tests/e2e/test_as_admin.yml
tests/e2e/test_as_tenant.yml
tests/func/tasks/tenant/seed/image.yml

* Bump `OS_BLOCK_STORAGE_DEFAULT_MICROVERSION` variable to `3.59` so the
`volume attachment` API can be used.
* Fix `guestfs-tools` package name for EL9 based vm.
* Fix assertion for `workloads.yaml` file content.
* Bump `CirrOS` image version to `0.6.3`.
* Fix the value of `disk_format` of the CirrOS image during its import.

dev: fixes for e2e tests

---

.github/workflows/consistency-functional.yml
os_migrate/galaxy.yml
toolbox/vagrant/ansible/roles/devstack/tasks/config.yml

With the release of the v2.4.x versions of the `openstack.cloud` collection, the support of tags for the `openstack.cloud.server` module has been added, but it seems that it broke our collection somehow.
We will revert this commit when the problem will be found and solved.

Pin `openstack.cloud` collection to the last v2.3.x available version

---

Makefile

While specifying `REUSE_TOOLBOX=1` the right tag will be used.

Fixed container tag in `toolbox-build`

---

os_migrate/roles/import_workloads/tasks/workload.yml

Set cloud_vars_src fact even when os_migrate_src_block_storage_api_version is not defined otherwise the next task failed while trying to reused the cloud_vars_src variable.

Set cloud_vars_src fact
